### ISSUE TITLE
List of Applications That Can Increase Graphic Designer Productivity

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#101]
Track Category: Design

[Hasanozie - List of Applications That Can Increase Graphic Designer Productivity.docx](https://github.com/topcoder-platform/thrive-submit/files/3976082/Hasanozie.-.List.of.Applications.That.Can.Increase.Graphic.Designer.Productivity.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by Dara-K** [comment]
This is an interesting list. I like it. However as a default PC user, I would like to see more options that are valid for me as well, not only for Mac users. Can you add new/ replace some  existing with some other apps who work nice and save time for windows too? I am sure there are similar tools for those related to designs (especially Aquarelo and Folio) 

Thank you!

**Comment by hasanozie** [comment]
Hi @Dara-K 
I have added several Windows applications that can increase designer productivity.

[Hasanozie - List of Applications That Can Increase Graphic Designer Productivity.docx](https://github.com/topcoder-platform/thrive-submit/files/3987505/Hasanozie.-.List.of.Applications.That.Can.Increase.Graphic.Designer.Productivity.docx)

**Comment by s-kaur** [comment]
Thank you for the articles, this is a very broad topic and there is no depth of point just a base paragraph of each app about, and this can be found easily anywhere in any design blog as well, we want a quality writing, something exciting to read but also bringing unique value, especially to Topcoder community, as these content are meant to them.
