### ISSUE TITLE
Modern idea to biult  E-Commerce site

### ISSUE THREAD

**Issue by ga20091049** [topcoder-platform/thrive-submit#102]
[E-commerce.docx](https://github.com/topcoder-platform/thrive-submit/files/3977477/E-commerce.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
https://www.ecommerce-nation.com/how-can-you-build-your-own-online-store-with-woocommerce-wordpress/

Copied from here, changed some words
