### ISSUE TITLE
Education technologies that inspire

### ISSUE THREAD

**Issue by nkoleva89** [topcoder-platform/thrive-submit#107]
Title: Education technologies that inspire
Author: Nadya Koleva
Track Category: Development

Over the past 10 years, education changed rapidly to follow the challenges of the future. The blackboards don't belong to the classroom anymore, and neither is the traditional paper textbook. Some even say the children of the future won't even need to know how to write by hand, as there's no need to.
Some of the most interesting technologies already well-integrated in the classrooms are the AR (Augmented Reality) technologies. In just a couple of years, AR technologies entered the travel, retail, real estate, automotive, entertainment, and healthcare industries, making everything faster and easier for both entrepreneurs and users. AR technologies now even have the power to bring the science directly in the classrooms and completely change the idea of how we used to see education in the past.
AR technologies for classrooms are already available as apps, which makes their use easier and convenient. AR technology supports teachers' jobs by helping them organize and prepare better classes, but it also makes homework far more interesting and attractive for students. There are already AR-enabled worksheets and now children feel much more comfortable and enthusiastic when it comes to homework assignments.  
AR apps are divided into two major classes:
Marker-based apps – image-based recognition – they use black&white markers to show the AR content. If you want to see the AR image, you have to point the camera of your smart device toward the object. As soon as the camera "catches" the marker, the app overlays the digital data and you can see the AR content. The marker-based AR apps are the most common and they find wide application in education.
Location-based apps – they don't need markers to work. The use of other data, such as the GPS coordinates of the user, an accelerometer, or a digital compass and then they overlay the AR objects on top of the real places. Such apps help you find a nearby hotel or restaurant, for example.

Creating augmented reality apps is a challenge, but there are some AR SDK which is quite easy to use, such as:
1. Vuforia (marker-based) is a good SDK for AR creation, it's pros are:
- good recognition of multiple objects.
-Easy creation of customized VuMarks, which have a better look than the typical QR-code
-Creation of a 3D geometric map of any kind of environment, using its Smart terrain feature.
-Easily turns images into a full-motion video that can be played directly on a target surface. 
2. The Roar (marker-based), it's pros are:
 -with this SDK you can turn into AR a full image or just part of it.
-Supported formats: 
.obj – for 3D model
.png, .jpg and .tga – for textures
.mtl – with all sets 
-you can add not only 3D image to your AR app but also text and audio, with good sound effects,
for better AR experience.
3.Google ARCore ( (marker-based)
-This SDK works well with Java/OpenGL and Unity.
-Excellent motion tracking – by using the camera, it "spots" the feature points in the room and thus the virtual objects are well-positioned.
-Good light estimation – this helps to build a very realistic AR 3D image.

With these easy to use and entertaining SDKs, even students could get involved easily in creating their own AR in no time. Both teachers and students all around the world are embracing inspiring technologies, like AR, as they know that the future belongs to the digital world.  And it's an amazing world out there, awaiting our children.

References:
1. (https://www.newgenapps.com/blog/6-amazing-ways-to-use-augmented-reality-in-the-classroom )
2. (https://www.mobileguardian.com/technology-and-the-classroom-of-the-future/ )
3. (https://www.infoq.com/articles/augmented-reality-best-skds/ )
4. Vuforia ( )
5. The Roar (https://www.ptc.com/en/products/augmented-reality/vuforia )
6. Google ARCore (https://developers.google.com/ar/ )

**Comment by nkoleva89** [comment]
[Education technologies that inspire.pdf](https://github.com/topcoder-platform/thrive-submit/files/3978573/Education.technologies.that.inspire.pdf)

**Comment by nkoleva89** [comment]
[Education technologies that inspire.pdf](https://github.com/topcoder-platform/thrive-submit/files/3978658/Education.technologies.that.inspire.pdf)

**Comment by kkartunov** [comment]
passed checks.

@nkoleva89 please also submit a link with the banner image for this article.

**Comment by nkoleva89** [comment]
Here's the pic : https://unsplash.com/photos/J1nc-LH0iBE

**Comment by billsedison** [comment]
@nkoleva89 Sorry, it's just an Introductory article, no much technical details. I think it is not that helpful for Thrive.

Sorry I can't accept it.

**Comment by nkoleva89** [comment]
ok
