### ISSUE TITLE
Effective Time Management For Beginner Graphic Designers

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#109]
Track Category: Design

[Hasanozie - Effective Time Management For Beginner Graphic Designers.docx](https://github.com/topcoder-platform/thrive-submit/files/3978820/Hasanozie.-.Effective.Time.Management.For.Beginner.Graphic.Designers.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by Dara-K** [comment]
This is more fit for a blog as well, because the tools described in the article are useful for any designer, developer, freelancer, even if he is a beginner or not. Would you like to publish this article on the blog?

**Comment by hasanozie** [comment]
Hi @Dara-K 
Of course, hopefully this article can be useful for anyone who sees it on the Topcoder blog

**Comment by fajarmln** [comment]
Sorry, we already have this kind of article since 2018:

https://www.topcoder.com/designing-your-time-for-topcoder-challenges/

content feels really similar, i will reject it.

**Comment by Dara-K** [comment]
Good catch @fajarmln , I forgot about that article. Sorry @hasanozie!
