### ISSUE TITLE
The giant language for projects: Python Programming beauty

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#11]
Hello, Kindly find the Corrected document here please.
zip-
[Thrivep2.zip](https://github.com/topcoder-platform/thrive-submit/files/3922198/Thrivep2.zip)
file with the files.
Regards.

**Comment by kkartunov** [comment]
Passed Plagiarism Check

**Comment by harshitmehta123** [comment]
Can you please improve your article to throw more light on where python is being used these days? What kind of projects? Also, talk about why python is being used now rather than Java or any other language being used earlier? @Rokit12

**Comment by Rokit12** [comment]
okay, let me fix it

**Comment by harshitmehta123** [comment]
Also, feel free to go further and talk about more basics and give readers some programs to try to understand their basics :)

**Comment by Rokit12** [comment]
okay, working on that

**Comment by Rokit12** [comment]
Kindly review this file now.
Regards
[thrive python.zip](https://github.com/topcoder-platform/thrive-submit/files/3955972/thrive.python.zip)

**Comment by Rokit12** [comment]
Kindly tell if the document is okay now

**Comment by harshitmehta123** [comment]
I think you should still work on the article a bit more to make it a bit advanced level. 
Basics of Python are available abundantly on the web. You should talk about why some XYZ structure is easy in python and that is the reason developers are moving to Python and not using Java for that anymore. 

Do you get the idea I am talking about?

**Comment by Rokit12** [comment]
OKAY, LET ME WORK ON IT

**Comment by Rokit12** [comment]
Hello, i have made it now from the previous basics to an advanced stage in python in comparison to other languages. Kindly check and tell.

Regards
[Thrivep2advance.zip](https://github.com/topcoder-platform/thrive-submit/files/3961388/Thrivep2advance.zip)

**Comment by harshitmehta123** [comment]
The content seems good now. We need to subtract some parts - I will edit the structure a bit and come back in a few days. In case you had like to improve let me know

**Comment by Rokit12** [comment]
Thank you for your acceptance. Thanks

**Comment by harshitmehta123** [comment]
I worked for a bit on the article - tried to find a structure but unfortunately it's very random. Here is my updated article. We need to have a structured flow in the article:

- Why python is Easy and Imp
- Basic Structures of Python
- Advance usage of Python (Well explained with examples and comments) 

@Rokit12 this article is for a newbie so we have to make sure things are clear to him with commentnts. 

For example - a newbie would not understand your numpy explnation :)

**Comment by Rokit12** [comment]
Okay i will work on it. For newbies

**Comment by Rokit12** [comment]
> I think you should still work on the article a bit more to make it a bit advanced level.
> Basics of Python are available abundantly on the web. You should talk about why some XYZ structure is easy in python and that is the reason developers are moving to Python and not using Java for that anymore.
> 
> Do you get the idea I am talking about?

I thought it was advanced as you had instructed not to make basics

**Comment by harshitmehta123** [comment]
Right, start from basics - move to advance.. it just needs a little more structuring

**Comment by harshitmehta123** [comment]
Let me attach the structuring I did to help you get an idea.
[TITLE_ The giant language for projects_ Python Programming beauty (1).docx](https://github.com/topcoder-platform/thrive-submit/files/3972438/TITLE_.The.giant.language.for.projects_.Python.Programming.beauty.1.docx)

**Comment by Rokit12** [comment]
Thanks, checking it

**Comment by Rokit12** [comment]
Hello, kindly check the one i have listed below. Tell me how about that with much introduction
[TITLE_ The Giant Programming Language – Python.docx](https://github.com/topcoder-platform/thrive-submit/files/3973673/TITLE_.The.Giant.Programming.Language.Python.docx)

**Comment by kkartunov** [comment]
@Rokit12 your articles will be no more considered for review. Please, stop submitting to this challenge. Your further submissions will be ignored.

**Comment by kkartunov** [comment]
@Rokit12 you have waisted enough of the time people dedicate to this project. This is the result https://github.com/topcoder-platform/thrive-submit/issues?q=is%3Aissue+author%3ARokit12+is%3Aclosed

**Comment by Rokit12** [comment]
apologies.
