### ISSUE TITLE
Benefit of the "Edit in Photoshop" Feature in Adobe XD For UI/UX Designers

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#110]
Track Category: Design

[Hasanozie - Benefit of the Edit-in-Photoshop Feature in Adobe XD For UI UX Designers.docx](https://github.com/topcoder-platform/thrive-submit/files/3981724/Hasanozie.-.Benefit.of.the.Edit-in-Photoshop.Feature.in.Adobe.XD.For.UI.UX.Designers.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by Dara-K** [comment]
I find it cool that Edit in Photoshop, from XD opens the PS and allows the edit back and forth, but the same things can be done in Photoshop by simple exporting and importing the image, so the features mentioned in the article belong to Photoshop and are pretty well used by now.

**Comment by hasanozie** [comment]
> I find it cool that Edit in Photoshop, from XD opens the PS and allows the edit back and forth, but the same things can be done in Photoshop by simple exporting and importing the image, so the features mentioned in the article belong to Photoshop and are pretty well used by now.


Thank you for reviewing this article :)
