### ISSUE TITLE
 ReactJS lazy code to code splitting: Is import really important in ReactJS

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#113]
[TITLE_ ReactJS lazy code to code splitting_ Is import really important in ReactJS.docx](https://github.com/topcoder-platform/thrive-submit/files/3983008/TITLE_.ReactJS.lazy.code.to.code.splitting_.Is.import.really.important.in.ReactJS.docx)

**Comment by Rokit12** [comment]
[TITLE_ ReactJS lazy code to code splitting_ Is import really important in ReactJS (1).docx](https://github.com/topcoder-platform/thrive-submit/files/3983022/TITLE_.ReactJS.lazy.code.to.code.splitting_.Is.import.really.important.in.ReactJS.1.docx)

**Comment by kkartunov** [comment]
@Rokit12 fails "Plagiarism was detected"

**Comment by Rokit12** [comment]
Which software for plagiarism?

**Comment by kkartunov** [comment]
@Rokit12 https://www.grammarly.com/plagiarism-checker

**Comment by Rokit12** [comment]
[TITLE_ ReactJS lazy code to code splitting_ Is import really important in ReactJS (1).docx](https://github.com/topcoder-platform/thrive-submit/files/3987569/TITLE_.ReactJS.lazy.code.to.code.splitting_.Is.import.really.important.in.ReactJS.1.docx)

**Comment by kkartunov** [comment]
@Rokit12 your article is < 500 words. We do not count titles, handles etc from header.

**Comment by Rokit12** [comment]
Sorry, it was error uploading. 
[TITLE_ ReactJS lazy code to code splitting_ Is import really important in ReactJS (3).docx](https://github.com/topcoder-platform/thrive-submit/files/3987969/TITLE_.ReactJS.lazy.code.to.code.splitting_.Is.import.really.important.in.ReactJS.3.docx)

**Comment by kkartunov** [comment]
@Rokit12 still under 500.

**Comment by kkartunov** [comment]
@Rokit12 please make sure **all your submissions** pass the requirements!
If you keep submitting spam you will be banned from the repo.
