### ISSUE TITLE
Important libraries for data scientists: Data analysis made easier

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#114]
[TITLE_ Important libraries for data scientists_ Data analysis made easier.docx](https://github.com/topcoder-platform/thrive-submit/files/3984093/TITLE_.Important.libraries.for.data.scientists_.Data.analysis.made.easier.docx)

**Comment by kkartunov** [comment]
Fails plagiarism check

**Comment by Rokit12** [comment]
let me fix please, it is just grammar correction

**Comment by Rokit12** [comment]
[TITLE_ Important libraries for data scientists_ Data analysis made easier (3).docx](https://github.com/topcoder-platform/thrive-submit/files/3987465/TITLE_.Important.libraries.for.data.scientists_.Data.analysis.made.easier.3.docx)

**Comment by kkartunov** [comment]
@Rokit12 still fails

**Comment by Rokit12** [comment]
How to fix this punctuation and style. I quit here
