### ISSUE TITLE
Programming languages used in Artificial intelligence: Systems made better

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#115]
[TITLE_ Programming languages used in Artificial intelligence_ Systems made better (1).docx](https://github.com/topcoder-platform/thrive-submit/files/3984442/TITLE_.Programming.languages.used.in.Artificial.intelligence_.Systems.made.better.1.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
The article doesn't help.

For the Java code, it just shows a simple sum of weighted factors.

For the C++ code, the `mlModel()` function is even empty. And there are some syntax erros in the given C++ code.

Actually, from the entire articfle, I can't see any reason or benefit that C++/Java has in the artificial intelligence.
