### ISSUE TITLE
Exploratory Data Analysis with Python

### ISSUE THREAD

**Issue by jlhopkins28160** [topcoder-platform/thrive-submit#116]
https://github.com/jlhopkins28160/TopcoderTHRIVE/EDAPython.docx

**Comment by kkartunov** [comment]
@jlhopkins28160 I get "Not Found" on this URL?

**Comment by jlhopkins28160** [comment]
Try this URL: http://github.com/jlhopkins28160/TopcoderTHRIVE/EDAPython.docx.

**Comment by jlhopkins28160** [comment]
Exploratory Data Analysis in Python:
[EDAPython.docx](https://github.com/topcoder-platform/thrive-submit/files/3987654/EDAPython.docx)

**Comment by jlhopkins28160** [comment]
I uploaded the article directly from my laptop's hard drive. This should help. I checked my repository and the general URL works.

**Comment by kkartunov** [comment]
@jlhopkins28160 fails check https://www.grammarly.com/plagiarism-checker

**Comment by jlhopkins28160** [comment]
How do I fix the plagiarism issue? I want any future submissions to have the highest quality.

**Comment by jlhopkins28160** [comment]
Exploratory Data Analysis in Python (Revision)
[EDAPython.docx](https://github.com/topcoder-platform/thrive-submit/files/3989957/EDAPython.docx)

**Comment by jlhopkins28160** [comment]
Exploratory Data Analysis in Python (Revised):
[EDAPython.docx](https://github.com/topcoder-platform/thrive-submit/files/3991696/EDAPython.docx)

**Comment by kkartunov** [comment]
@jlhopkins28160 still getting the failed check.

**Comment by jlhopkins28160** [comment]
Exploratory Data Analysis in Python (2nd revision)
[EDAPython.docx](https://github.com/topcoder-platform/thrive-submit/files/3993145/EDAPython.docx)

**Comment by kkartunov** [comment]
@jlhopkins28160 sorry but still red for me

**Comment by jlhopkins28160** [comment]
Exploratory Data Analysis in Python (3rd revision):
[EDAPython.docx](https://github.com/topcoder-platform/thrive-submit/files/3996162/EDAPython.docx)

**Comment by kkartunov** [comment]
@jlhopkins28160 sorry but it fails again. Just closing this as it won't work this way. Try another topic
