### ISSUE TITLE
Understanding Random Forest and Hyper Parameter tuning

### ISSUE THREAD

**Issue by tarushi96** [topcoder-platform/thrive-submit#119]
[tarushi_pysark_article2.docx](https://github.com/topcoder-platform/thrive-submit/files/3987817/tarushi_pysark_article2.docx)

Hi, 
uploading an article on understanding Random Forests and hyper parameter tuning for them.

**Comment by kkartunov** [comment]
@tarushi96 fails check https://www.grammarly.com/plagiarism-checker
