### ISSUE TITLE
 Importance of LISP and Prolog programming language: Are they needed still worth

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#121]
[TITLE_ Importance of LISP and Prolog programming language_ Are they needed still worth.docx](https://github.com/topcoder-platform/thrive-submit/files/3989146/TITLE_.Importance.of.LISP.and.Prolog.programming.language_.Are.they.needed.still.worth.docx)

**Comment by Rokit12** [comment]
Hello, Kindly i have advanced the document.
[TITLE_ Importance of LISP and Prolog programming language_ Are they needed still worth (3).docx](https://github.com/topcoder-platform/thrive-submit/files/3991267/TITLE_.Importance.of.LISP.and.Prolog.programming.language_.Are.they.needed.still.worth.3.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
This article doesn't help either. I don't see any obvious importance or advantages of LISP or Prolog.

If you want to write such articles, please compare them with other popular languages (like python, R etc) and highlight their advantages or importance.

**Comment by Rokit12** [comment]
cool
