### ISSUE TITLE
New programming language for developers:  Graphical User Interface made easier by Dragon

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#123]
[Thrive8.zip](https://github.com/topcoder-platform/thrive-submit/files/3990090/Thrive8.zip)

**Comment by Rokit12** [comment]
Here is the corrected article.
[TITLE_ New programming language for developers_  Graphical User Interface made easier by Dragon (1).docx](https://github.com/topcoder-platform/thrive-submit/files/3990098/TITLE_.New.programming.language.for.developers_.Graphical.User.Interface.made.easier.by.Dragon.1.docx)

**Comment by Rokit12** [comment]
Hello, kindly check the document below. Regards.
[TITLE_ New programming language for developers_  Graphical User Interface made easier by Dragon (3).docx](https://github.com/topcoder-platform/thrive-submit/files/3991260/TITLE_.New.programming.language.for.developers_.Graphical.User.Interface.made.easier.by.Dragon.3.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
@Rokit12 You copied or translated the article from here http://www.zijin.net/news/tech/1119061.html (in Chinese)

See your code
```
two()
four()
eight()
func one() {
showln “two”}
func four() {
     	 showln “four”}
func eight() {
 showln “eight”}

```
And the sample code in the Chinese article
![image](https://user-images.githubusercontent.com/5657467/71473587-7f63f100-2812-11ea-97f6-303d9e0c1e7d.png)


You changed the function name from `one()` `two()` `three()` to `two()` `four()` `eight()` then try to cheat the plagarism checker!!

YOU SHOULD STOP DOING THIS!

**Comment by Rokit12** [comment]
I know nothing about chinese, i actually referenced the articles where i learned about it here. The dragon site only i used. Kindly check here:https://dragon-lang.org/. The programming language original author site please

**Comment by billsedison** [comment]
@Rokit12 Ok, but anyway why did you change function names in the sample code from `one()` `two()` `three()` to `two()` `four()` `eight()`.

The code snippet you provided is very similar to the Chinese site.

And even the calculator screenshot, it is not from you. As per the rule, if you cited the images from elsewhere, you should provide the link.

**Comment by Rokit12** [comment]
The code is from the coding i was trying out in my program. But it is okay, i think coincidence.
