### ISSUE TITLE
React JS to include data in suspense: Declaring data to be rendered through API

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#124]
[TITLE_ React JS to include data in suspense_ Declaring data to be rendered through API (3).docx](https://github.com/topcoder-platform/thrive-submit/files/3990107/TITLE_.React.JS.to.include.data.in.suspense_.Declaring.data.to.be.rendered.through.API.3.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
Duplicated with https://github.com/topcoder-platform/thrive-submit/issues/66

You just removed the code snippet that I pointed out is plagiarism.

Anyway, the format of the overall article looks pretty bad and the sentences are very oral (like gonna, wanna etc).

And for the content looks not good, you should write more concrete examples for ReactJS and axio.
