### ISSUE TITLE
What and How of Backpropgation algorithm

### ISSUE THREAD

**Issue by ruchikakhemka** [topcoder-platform/thrive-submit#125]
Let's understand what back propagation algorithm is, Why it is required and how it works.

**Comment by ruchikakhemka** [comment]
[What and How of BackPropagation.docx](https://github.com/topcoder-platform/thrive-submit/files/4013700/What.and.How.of.BackPropagation.docx)


Data Science

**Comment by kkartunov** [comment]
fails checks
