### ISSUE TITLE
Introduction to Data Visualization with Grafana

### ISSUE THREAD

**Issue by rafiudd** [topcoder-platform/thrive-submit#126]
Link: https://docs.google.com/document/d/1rqzw_w7wdEN4lH6VLq6wnvBJWGgDCfwH87bawQTayts/edit?usp=sharing

**Comment by rafiudd** [comment]
Hi, can you check it again please @kkartunov

**Comment by kkartunov** [comment]
@rafiudd it fails now the Plagiarism check. Sorry, closing this as it won't work this way.
