### ISSUE TITLE
tutorial on how to make a donut chart

### ISSUE THREAD

**Issue by dewiep925** [topcoder-platform/thrive-submit#127]
Track Category : Design
[tutorial donut chart.pdf](https://github.com/topcoder-platform/thrive-submit/files/3991195/tutorial.donut.chart.pdf)
[https://docs.google.com/document/d/1ZKBAlthnYiCtE3awfOBt-dcoEXnkTMKTiEFSDNWqb8o/edit](url)

**Comment by dewiep925** [comment]
Track Category : Design
[tutorial donut chart.docx](https://github.com/topcoder-platform/thrive-submit/files/3991035/tutorial.donut.chart.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by fajarmln** [comment]
We already have a tutorial on how to create donut chart in our "Topcoder Design Newsletter - September 15th", the newsletter will be imported to THRIVE later, so this tutorial will be rejected due to content similarity.
