### ISSUE TITLE
Write Code Efficiently with Live Template - Android Studio

### ISSUE THREAD

**Issue by DjakaTechnology** [topcoder-platform/thrive-submit#140]
[Write Code Efficiently with Live Template - Android Studio.docx](https://github.com/topcoder-platform/thrive-submit/files/3991192/Write.Code.Efficiently.with.Live.Template.-.Android.Studio.2.docx)

**Comment by DjakaTechnology** [comment]
Track: Development

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
@DjakaTechnology 

Looks the GIF doesn't play in the MS Word, can you please provide the GIF separately, so that we can include in the published article? Thanks

![image](https://user-images.githubusercontent.com/5657467/71474054-af13f880-2814-11ea-84ea-e3bd0cb44f2b.png)

**Comment by DjakaTechnology** [comment]
@billsedison here's the gif
[gif.zip](https://github.com/topcoder-platform/thrive-submit/files/4004508/gif.zip)

**Comment by billsedison** [comment]
@DjakaTechnology Double checked this is the common tricks of the JetBrains IntelliJ series IDE, not just for Android Studio
https://www.jetbrains.com/help/webstorm/using-live-templates.html
https://www.jetbrains.com/help/phpstorm/template-variables.html
https://www.jetbrains.com/help/idea/creating-and-editing-live-templates.html
https://www.raywenderlich.com/4979242-live-templates-in-android-studio-getting-started

It's good, but it's pretty easy to learn elsewhere as it's just a trick of the IDE tools, this is not the technology tutorial, so this is not what we are looking for THRIVE.

Sorry, I can't accept your article.
