### ISSUE TITLE
Utilizing The Adobe XD Shortcut To Speed Up Your Design Workflow

### ISSUE THREAD

**Issue by wahyu-ts** [topcoder-platform/thrive-submit#145]
Work In Progress

**Comment by wahyu-ts** [comment]
Track Category: Design

https://docs.google.com/document/d/18Wu_eqXKZydqwB52rMy0cCO18rVg77cPHXxVZQQFWUs/edit?usp=sharing

**Comment by wahyu-ts** [comment]
Hi @kkartunov,

Kindly check again the link below:

https://docs.google.com/document/d/18Wu_eqXKZydqwB52rMy0cCO18rVg77cPHXxVZQQFWUs/edit?usp=sharing

As per checking, it passed the Plagiarism Checker.

**Comment by kkartunov** [comment]
@wahyu-ts passes checks now

**Comment by Dara-K** [comment]
Hi @wahyu-ts!
Having an article about Adobe XD shortcuts is not something that can't be quickly learned from the tool itself. They are practical indeed, but not a fit for the THRIVE design articles. Sorry.
