### ISSUE TITLE
Shared Ingradients of Great UI Design

### ISSUE THREAD

**Issue by irfanrosandi** [topcoder-platform/thrive-submit#146]
https://docs.google.com/document/d/1r7V92-wPU-WJWcR6tUNAiAv7A6DDOo69b6i-jXWfqSk/edit?usp=sharing

**Comment by kkartunov** [comment]
fails checks

**Comment by irfanrosandi** [comment]
why this is plagiarism? I didn't copy/take it from other source? this is pure in my head.

**Comment by kkartunov** [comment]
It fails the check https://www.grammarly.com/plagiarism-checker. Sorry, we can't accept it.
