### ISSUE TITLE
Various Types of Graphic Design That You Need to Know

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#149]
Track Category: Design

[Hasanozie - Various Types of Graphic Design That You Need to Know.docx](https://github.com/topcoder-platform/thrive-submit/files/3993807/Hasanozie.-.Various.Types.of.Graphic.Design.That.You.Need.to.Know.docx)

**Comment by fajarmln** [comment]
I've read the article and the knowledge inside this article is very basic and not meet the THRIVE standard, sorry, but this article will be rejected.
