### ISSUE TITLE
Introduction to Regression Modeling with Weka

### ISSUE THREAD

**Issue by jlhopkins28160** [topcoder-platform/thrive-submit#152]
Work in Progress

**Comment by jlhopkins28160** [comment]
Category: Data Science
[Regression_Weka.docx](https://github.com/topcoder-platform/thrive-submit/files/4013633/Regression_Weka.docx)

**Comment by kkartunov** [comment]
fails checks

**Comment by jlhopkins28160** [comment]
Category: Data Science
[Weka.docx](https://github.com/topcoder-platform/thrive-submit/files/4024202/Weka.docx)

**Comment by kkartunov** [comment]
@jlhopkins28160 fails checks again. Sorry, closing it.
