### ISSUE TITLE
Math with Python via SymPy

### ISSUE THREAD

**Issue by jlhopkins28160** [topcoder-platform/thrive-submit#153]
Work in Progress

**Comment by jlhopkins28160** [comment]
Category: Development
[SymPy.docx](https://github.com/topcoder-platform/thrive-submit/files/4003774/SymPy.docx)

**Comment by kkartunov** [comment]
fails checks

**Comment by jlhopkins28160** [comment]
Category: Development
[SymPy.docx](https://github.com/topcoder-platform/thrive-submit/files/4024219/SymPy.docx)

**Comment by kkartunov** [comment]
@jlhopkins28160 fails again. Sorry, we can't process this anymore.
