### ISSUE TITLE
Understanding AWS concepts.

### ISSUE THREAD

**Issue by shubham-dota** [topcoder-platform/thrive-submit#161]
Track Category: Development
[Understanding AWS concepts..docx](https://github.com/topcoder-platform/thrive-submit/files/3997875/Understanding.AWS.concepts.docx)
[AWS image resource.zip](https://github.com/topcoder-platform/thrive-submit/files/3997879/AWS.image.resource.zip)

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
@shubham-dota This article is not helpful. We can easily get these concepts from the AWS official site. So I can't accept your article, sorry.
