### ISSUE TITLE
How To Create Clock Icon Using Affinity Designer

### ISSUE THREAD

**Issue by yopi2207** [topcoder-platform/thrive-submit#163]
Track Category: Design

[How To Create Clock Icon Using Affinity Designer.pdf](https://github.com/topcoder-platform/thrive-submit/files/3998445/How.To.Create.Clock.Icon.Using.Affinity.Designer.pdf)

**Comment by fajarmln** [comment]
Rejected Review, the reason:

- Clock icon tutorial is very general and lots of it already available in the internet as an article or video tutorial

- Affinity designer is not standard tool that we use in Topcoder
