### ISSUE TITLE
Getting started with MongoDB

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/thrive-submit#164]
Category: Development

[mongodb_basics.md.zip](https://github.com/topcoder-platform/thrive-submit/files/3998466/mongodb_basics.md.zip)

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
@anu0012 This article is not that helpful. The official site provides more concrete tutorials to help member getting started: https://docs.mongodb.com/manual/tutorial/getting-started/

So I can't accept this article, sorry.
