### ISSUE TITLE
The Advantage of Design Challenge at Topcoder

### ISSUE THREAD

**Issue by davidhumanize** [topcoder-platform/thrive-submit#173]
Track Category : Design

[david.humanize - The Advantage of Design Challenge at Topcoder.docx](https://github.com/topcoder-platform/thrive-submit/files/4003846/david.humanize.-.The.Advantage.of.Design.Challenge.at.Topcoder.docx)

**Comment by davidhumanize** [comment]
Hi guys!
If you had any feedback please comment, i will improving this article as best as i can.

**Comment by kkartunov** [comment]
passed checks

**Comment by Dara-K** [comment]
Hi @davidhumanize 
I like your article but it has a lot of content overlapping with a previously written article: https://www.topcoder.com/why-be-a-topcoder-designer/
Sorry about that!
