### ISSUE TITLE
Getting started with Markdown

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/thrive-submit#178]
Category: Development

[getting_started_markdown.md.zip](https://github.com/topcoder-platform/thrive-submit/files/4006351/getting_started_markdown.md.zip)

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
@anu0012 This article is not that helpful. There are too many markdown start guide, like https://guides.github.com/features/mastering-markdown/

We don't need a markdown tutorial actually.
