### ISSUE TITLE
Test Automation - Connect Android and iOS Device Wireless

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#181]
[Test Automation - Connect Android and iOS Device Wireless.docx](https://github.com/topcoder-platform/thrive-submit/files/4006759/Test.Automation.-.Connect.Android.and.iOS.Device.Wireless.docx)

**Comment by kkartunov** [comment]
Fails check

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
