### ISSUE TITLE
Why Choose Topcoder ?

### ISSUE THREAD

**Issue by dewiep925** [topcoder-platform/thrive-submit#182]
Track Category : Topcoder
https://docs.google.com/document/d/1_UgadcYmAKJUvEmo7D5GOaxpKk2OP9jjiL1QAFfcXCI/edit

**Comment by kkartunov** [comment]
@dewiep925 can't access this one

**Comment by dewiep925** [comment]
Oh, I'm sorry @kkartunov .. Maybe try this one 
[Why Choose Topcoder ?.pdf](https://github.com/topcoder-platform/thrive-submit/files/4006856/Why.Choose.Topcoder.pdf)

**Comment by dewiep925** [comment]
@kkartunov  would you please check my article 
[Why Choose Topcoder ?.pdf](https://github.com/topcoder-platform/thrive-submit/files/4008523/Why.Choose.Topcoder.pdf)

**Comment by kkartunov** [comment]
Hi @dewiep925,
Thank You for your article. We are looking for more technical orientated articles for Thrive that is why can't accept it. We will consider it for the blog and eventually let you know.
