### ISSUE TITLE
The Best Personal Branding for UI / UX Designers

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#183]
Track Category: Design

[Hasanozie - The Best Personal Branding for UI  UX Designers.docx](https://github.com/topcoder-platform/thrive-submit/files/4007210/Hasanozie.-.The.Best.Personal.Branding.for.UI.UX.Designers.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by hasanozie** [comment]
Google docs link for this article

https://docs.google.com/document/d/1DWiEj-ibULK7fSODueVLfkrvkVwFhg3VBCQ_15nuMNM/edit?usp=sharing

**Comment by fajarmln** [comment]
Thank you for the article @hasanozie, but this content will encourage members to leave topcoder and start their own personal business or branding design agency which something that we want to have happened, we want people to get engaged more with topcoder, not leave it. 

I will reject and close this ticket.
