### ISSUE TITLE
An introduction to Game development using UNITY 

### ISSUE THREAD

**Issue by ishitakanani** [topcoder-platform/thrive-submit#184]
Work Completed.

**Comment by ishitakanani** [comment]
Category : Development
[An_Introduction_To_Game_Development_With_Unity.docx](https://github.com/topcoder-platform/thrive-submit/files/4013116/An_Introduction_To_Game_Development_With_Unity.docx)

**Comment by billsedison** [comment]
@ishitakanani Copied from here https://medium.com/free-code-camp/the-ultimate-beginners-guide-to-game-development-in-unity-f9bfe972c2b5
