### ISSUE TITLE
Hyperparameter Tuning algorithms

### ISSUE THREAD

**Issue by asdspal** [topcoder-platform/thrive-submit#187]
This article includes a small introduction to some algorithms used in hyperparameter tuning and their implementation with available tools & libraries.
The HTML file includes code blocks and figures also apart from text content so, I've included a separate txt file containing only text for easier plagiarism check.

[Thrive submission_ Hyperparamter tuning.docx](https://github.com/topcoder-platform/thrive-submit/files/4007879/Thrive.submission_.Hyperparamter.tuning.docx)
[Hyperparameter-Tuning.html](https://github.com/asdspal/articles-thrive/blob/master/hyper%20parameter%20tuning.html)
[text-content.txt](https://github.com/asdspal/articles-thrive/blob/master/text-content.txt)

**Comment by kkartunov** [comment]
@asdspal please submit a doc/pdf/md file with the article. I can't process your HTML

**Comment by asdspal** [comment]
Here is the pdf file
[hyper parameter tuning.pdf](https://github.com/topcoder-platform/thrive-submit/files/4008260/hyper.parameter.tuning.pdf)

**Comment by kkartunov** [comment]
@asdspal fails plagiarism check

**Comment by asdspal** [comment]
Are you using Grammarly plagiarism checker?
This is the result of directly uploading the text-content.txt on grammarly
![grammarly](https://user-images.githubusercontent.com/10200210/71593304-84e67180-2b59-11ea-9bed-e254c4e1f7f8.jpg)

**Comment by kkartunov** [comment]
yes @asdspal 
unfortunately I can't confirm your result.
