### ISSUE TITLE
Why Your Design Is Not Chosen As Winner In The UI Design Challenge

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#188]
Track Category: Design

[Hasanozie - Why Your Design Is Not Chosen As Winner In The UI Design Challenge.docx](https://github.com/topcoder-platform/thrive-submit/files/4008108/Hasanozie.-.Why.Your.Design.Is.Not.Chosen.As.Winner.In.The.UI.Design.Challenge.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by hasanozie** [comment]
Google docs link for this article

https://docs.google.com/document/d/1pRAxXAE-Ya4Z6n1PikRiMjdulyWNQREd36wj85eUenc/edit?usp=sharing

**Comment by fajarmln** [comment]
Thank you for the article @hasanozie, but this article content is not deep enough and useful for THRIVE content. I will reject and close this ticket.
