### ISSUE TITLE
Quantum computing for beginners

### ISSUE THREAD

**Issue by bhagvank** [topcoder-platform/thrive-submit#191]
This article is for beginners who want to know about quantum computing.

My article link below:
https://docs.google.com/document/d/1p3b09KhLpypAwipQGI4oOpAu2cKw7XaR5FJPWfp5KZ0/edit?usp=sharing

**Comment by kkartunov** [comment]
@bhagvank we have a similar article already in Thrive. Thank You.

**Comment by kkartunov** [comment]
https://www.topcoder.com/quantum-computing-for-beginners-what-you-need-to-know/

**Comment by bhagvank** [comment]
changed the title .. the content is different from topcoder's article...  github repo has the code for Mutliquibutsystem with different quantum gates. https://docs.google.com/document/d/1p3b09KhLpypAwipQGI4oOpAu2cKw7XaR5FJPWfp5KZ0/edit?usp=sharing
