### ISSUE TITLE
How to Make the Best Form for UI / UX Design

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#193]
Track Category: Design

[Hasanozie - How to Make the Best Form for UI  UX Design.docx](https://github.com/topcoder-platform/thrive-submit/files/4010373/Hasanozie.-.How.to.Make.the.Best.Form.for.UI.UX.Design.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by hasanozie** [comment]
Google docs link for this article

https://docs.google.com/document/d/15DxzvvMm6K2HfOsR6QS6L6s9enjlzVzLsRscf6p_EYk/edit?usp=sharing

**Comment by fajarmln** [comment]
This kind of article about how to create the best form design can be found a lot in the internet and not really interesting for us (not giving additional value for THRIVE), I will reject and close this ticket.
