### ISSUE TITLE
Topcoder Phenomenon to Change Your Way of Life

### ISSUE THREAD

**Issue by abilabbas** [topcoder-platform/thrive-submit#194]
Track: Topcoder

https://docs.google.com/document/d/1Hl5zlCEiJMk9oB3hMlUfevcwoNT_srjKIzHoilg9rik/edit?usp=sharing

**Comment by kkartunov** [comment]
@abilabbas ,
Thank You for your article. We are looking for more technical orientated articles for Thrive that is why can't accept it. We will consider it for the blog and eventually let you know.
