### ISSUE TITLE
The International Design World Cup - TCO Final!

### ISSUE THREAD

**Issue by iqbalhood** [topcoder-platform/thrive-submit#195]
Track : Design
Work In Progress

Article :
https://docs.google.com/document/d/1J85MdxAoFHUKm8tuBwgUYeagySDWIgKCwTGsXRTecfI/edit?usp=sharing

**Comment by kkartunov** [comment]
@iqbalhood thank you but this article is not suitable for Thrive. We are looking for more detailed in-deep technical submissions.
