### ISSUE TITLE
Screen Recording Tools

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#198]
[Screen Recording Tools.docx](https://github.com/topcoder-platform/thrive-submit/files/4010681/Screen.Recording.Tools.docx)
This document contains details of various screen recording tools which helps during QA

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
