### ISSUE TITLE
TestNG Testing Framework

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#199]
[TestNG Testing Framework.docx](https://github.com/topcoder-platform/thrive-submit/files/4010774/TestNG.Testing.Framework.docx)
This document contains about TestNG Framwork

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
