### ISSUE TITLE
Title: Cucumber Tool - BDD Behavior Driven Development

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#200]
[Cucumber Tool - BDD Behavior Driven Development.docx](https://github.com/topcoder-platform/thrive-submit/files/4010906/Cucumber.Tool.-.BDD.Behavior.Driven.Development.docx)
Attached document about Cucumber Tool BDD

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
