### ISSUE TITLE
Getting started with Firebase Cloud Firestore using Python

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/thrive-submit#201]
Category: Development

[getting_started_firebase.md.zip](https://github.com/topcoder-platform/thrive-submit/files/4010909/getting_started_firebase.md.zip)

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
The article is not helpful. The official getting start guide provides more thorough steps and also provides more languages other than python.

https://firebase.google.com/docs/firestore/quickstart

**Comment by kkartunov** [comment]
Thanks to @anu0012 and @billsedison. Closing this one
