### ISSUE TITLE
R and R Studio: Regression

### ISSUE THREAD

**Issue by jlhopkins28160** [topcoder-platform/thrive-submit#204]
Track: Data Science
[Regression.docx](https://github.com/topcoder-platform/thrive-submit/files/4011621/Regression.docx)

Track: Data Science (Updated today for Appeals phase):
[Regression.docx](https://github.com/topcoder-platform/thrive-submit/files/4016193/Regression.docx)

Updated to rectify any issues with plagiarism.

**Comment by kkartunov** [comment]
fails checks

**Comment by jlhopkins28160** [comment]
Category: Data Science
[Regression.docx](https://github.com/topcoder-platform/thrive-submit/files/4024181/Regression.docx)

**Comment by kkartunov** [comment]
@jlhopkins28160 fails again. Sorry, but we can't process this anymore.
