### ISSUE TITLE
Online Transportation Technology

### ISSUE THREAD

**Issue by riskaand** [topcoder-platform/thrive-submit#207]
Along with the change in times, Transportation technology in Indonesia 
increase very significantly. It proven, with the presence one of transportation technology which make the users feel easier to go to some places with no trouble or buy something without go anywhere. Or we can write “ Just Sit and Enjoy it”

The concrete example is Taxibike or we can call it with Transportation Online. It began from Nadiem Makarim experience, the founder of Gojek as Biggest Transportation Online Company in Indonesia. He used taxibike to go through Jakarta’s traffic jam. He saw there was a business opportunity in this case. He started built call center to connect drivers and passengers on 2010. This development, got positive feedback from the drivers, so they decided to join with Gojek. This was a consideration for investors to develop Gojek. Now, Gojek has very innovations, such as application that you can download for free on iOS and android, progressing memorable logo design, add several new menus, top up balance, developed in many cities in Indonesia, payment online system, disable drivers are very welcome, shopping service, and drivers learn to use Sign Language to make Deaf Users feel easier make communication with the drivers. In many countries, online transportations are so close with the people.  The companies are also upgrade their services to customers. Like change motorcycle to bigger, give discount, even voucher for promo. 

I believe, creative and innovative make everything better and can be received by the general people with no limits. Gojek is not one and only Online Transportation technology in Indonesia. Other companies like Grab and many little taxibikes also exist in this country.

Online Transportation Technology can be one of solutions to reduce Traffic Jam because population growth every year. This technology has been adjusted with safety standards according to applicable law in this Country.

**Comment by fajarmln** [comment]
This content is not related to THRIVE, make sure to read the requirement about article topics that we can accept for THRIVE before start writing an article, thank you.
