### ISSUE TITLE
aws cost reduction

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#21]
[AWS Cost_reduction_process.docx](https://github.com/topcoder-platform/thrive-submit/files/3922947/AWS.Cost_reduction_process.docx)

**Comment by kkartunov** [comment]
@t0070926 please make sure it passes Plagiarism Check https://www.grammarly.com/plagiarism-checker

**Comment by t0070926** [comment]
`
[aws_cost_reduction_process.docx](https://github.com/topcoder-platform/thrive-submit/files/3927310/aws_cost_reduction_process.docx)
`

**Comment by t0070926** [comment]
Uploaded latest document after passing tool
