### ISSUE TITLE
Online Transportation Technology

### ISSUE THREAD

**Issue by riskaand** [topcoder-platform/thrive-submit#210]
Hello
I finished My Article

Tittle : Online Transport Technology
Track Category : Data Scient

https://docs.google.com/document/d/1oKwGeUUROKkYiDjMeP4eVoLVFjmz110RgSSBtrYGT_o/edit?usp=sharing

**Comment by kkartunov** [comment]
@riskaand not suitable for Thrive and is below min length requirement.
