### ISSUE TITLE
How To Make UI / UX Designs For Foldable Smartphones That Have Bigger Screens

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#211]
Track Category: Design

[Hasanozie - How To Make UI UX Designs For Foldable Smartphones That Have Bigger Screens.docx](https://github.com/topcoder-platform/thrive-submit/files/4012217/Hasanozie.-.How.To.Make.UI.UX.Designs.For.Foldable.Smartphones.That.Have.Bigger.Screens.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by hasanozie** [comment]
Google docs link for this article

https://docs.google.com/document/d/11xYNfm3ZdxLNkffitX-I2ulwdm6hgIeoS5wnaZ3_k4E/edit?usp=sharing

**Comment by fajarmln** [comment]
Thank you for the article. However, in my opinion, the foldable phone screen size is the same thing as a tablet. So, it will be more useful if you create tutorial on how to create UI that works in two different resolutions (when the foldable phone is folded and opened). Right now, I believe this article does not bring much value, I will reject the article and close the ticket
