### ISSUE TITLE
5 Ways to Improve your UI skills and career by participating in Topcoder Design Challenge

### ISSUE THREAD

**Issue by iqbalhood** [topcoder-platform/thrive-submit#212]
@kkartunov 
Hello Kiril,

I finished the article:

Track : Design

Article:
https://docs.google.com/document/d/1AzWGmTnj6bLaaPH4XFb_a9bedX_CR-Z9Jry3TmZrivQ/edit?usp=sharing

Thank You :)

**Comment by kkartunov** [comment]
passed checks

**Comment by fajarmln** [comment]
The article topic is good to explain how designers can utilize topcoder to its maximum potential. Can you also add some new points such as:

- Build Portfolio based on real world problem
- Being certified (rating system and winning statistic history)
- Learning in THRIVE, UI/UX Design Bootcamp, and UI Workshop

**Comment by kkartunov** [comment]
@iqbalhood  please complete the requested in a day or we will need to close this one.

**Comment by iqbalhood** [comment]
okay sir @kkartunov

**Comment by iqbalhood** [comment]
Hello sir @fajarmln @kkartunov ,
I Have modified the article. You can check it here 

https://docs.google.com/document/d/1AzWGmTnj6bLaaPH4XFb_a9bedX_CR-Z9Jry3TmZrivQ/edit?usp=drivesdk

Thanks

**Comment by Dara-K** [comment]
@iqbalhood  @fajarmln  Hey guys,
I have just read this article. While it has some great points and new ones, we already have a similar article written back in 2017 https://www.topcoder.com/why-be-a-topcoder-designer/

Besides, the article looks more like a better fit for a blog than THRIVE as it's not bringing any educational content for a designer. It helps guiding a person into the Topcoder design world, but not learning anything about design itself - methods, ways of thinking, tools, etc.

I believe we **should** reject this.  (cc @fajarmln)

**Comment by fajarmln** [comment]
Thank you for the reference @Dara-K. 

I agree with it, let's close this ticket.

**Comment by iqbalhood** [comment]
Okay, No Problem, Thanks for the review @fajarmln @Dara-K
