### ISSUE TITLE
Logcat Command-Line Tool

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#214]
[Logcat command-line tool.docx](https://github.com/topcoder-platform/thrive-submit/files/4012488/Logcat.command-line.tool.docx)
Attached document about - Logcat Command-Line Tool
Android logcat is a command-line tool that dumps a log of system messages.

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
