### ISSUE TITLE
Agile Project Test Strategy

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#215]
[Agile Project Test Strategy.docx](https://github.com/topcoder-platform/thrive-submit/files/4012492/Agile.Project.Test.Strategy.docx)

The attached document contains about Agile Project Test Strategy

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
