### ISSUE TITLE
Android File Transfer – macOS  - Windows - Chromebook

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#216]
[Android File Transfer – macOS  - Windows - Chromebook.docx](https://github.com/topcoder-platform/thrive-submit/files/4012501/Android.File.Transfer.macOS.-.Windows.-.Chromebook.docx)

The attached document content contains about Android File Transfer – macOS  - Windows - Chromebook

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
