### ISSUE TITLE
Debug a Wear OS app

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#217]
[Debug a Wear OS app.docx](https://github.com/topcoder-platform/thrive-submit/files/4012503/Debug.a.Wear.OS.app.docx)

The attached document contains content about Debug a Wear OS app

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
