### ISSUE TITLE
Appium Open Source Test Automation Framework

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#218]
[Appium Open Source Test Automation Framework.docx](https://github.com/topcoder-platform/thrive-submit/files/4012524/Appium.Open.Source.Test.Automation.Framework.docx)

The attached document contains content about Appium Open Source Test Automation Framework

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
