### ISSUE TITLE
Katalon Recorder

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#219]
[Katalon Recorder.docx](https://github.com/topcoder-platform/thrive-submit/files/4012549/Katalon.Recorder.docx)

The attached document contains content about Katalon Recorder

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
