### ISSUE TITLE
 Developers worth: How to be a front-end developer

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#22]
Hi, 
Kindly find the below docs in the zip-file.
Regards
[frontdev.zip](https://github.com/topcoder-platform/thrive-submit/files/3922981/frontdev.zip)

**Comment by kkartunov** [comment]
Passed Plagiarism Check.

**Comment by billsedison** [comment]
@Rokit12 It is just a simple introduction of React, Angular and Vue, and only described the environment setup briefly (Too brief, just introduced `npm install` and create the app).

And there is a technical error, **AngularJS** (Angular 1.x) and **Angular** (Angular 2+) are different, you mentioned **AngularJS** but in the command description, it's to install Angular CLI.

We cannot accept this article as we can easily search the introduction and environment setup via Google, the article is not that helpful.

Sorry.

**Comment by Rokit12** [comment]
okay, No worries
