### ISSUE TITLE
Maven vs Gradle Build Tool 

### ISSUE THREAD

**Issue by jganeshram** [topcoder-platform/thrive-submit#221]
[Maven vs Gradle Build Tool .docx](https://github.com/topcoder-platform/thrive-submit/files/4012690/Maven.vs.Gradle.Build.Tool.docx)

The attached document content contains about Maven vs Gradle Build Tool

**Comment by kkartunov** [comment]
fails checks

**Comment by jganeshram** [comment]
@kkartunov - You mean "fails checks" referring to grammarly plagiarism checker. If that so it is expect for all technical article. Because it contains syntax. I have put 2 hour effort to create one. Any technical person can understand this. Kindly re-review.
