### ISSUE TITLE
Mutli Qubitsystem with different quantum gates.

### ISSUE THREAD

**Issue by bhagvank** [topcoder-platform/thrive-submit#222]
https://docs.google.com/document/d/1p3b09KhLpypAwipQGI4oOpAu2cKw7XaR5FJPWfp5KZ0/edit?usp=sharing

**Comment by kkartunov** [comment]
passed checks

**Comment by billsedison** [comment]
@kkartunov I think it should be the Data Science track. @harshitmehta123 Can you please check?

**Comment by harshitmehta123** [comment]
We already have a an article on Quantum Computing for Beginners. https://www.topcoder.com/quantum-computing-for-beginners-what-you-need-to-know/

Also, we have a series on Quantum Algorithms written by you :)
