### ISSUE TITLE
The THRIVE Rule to be a better programmer

### ISSUE THREAD

**Issue by ishitakanani** [topcoder-platform/thrive-submit#231]
Track Category : Topcoder
[Thrive_rule_to_be_a_better_programmer.docx](https://github.com/topcoder-platform/thrive-submit/files/4013523/Thrive_rule_to_be_a_better_programmer.docx)

**Comment by kkartunov** [comment]
@ishitakanani this article is not suitable for Thrive. We are looking for technical detailed articles and won't accept "How to" type of wishes. Thanks
