### ISSUE TITLE
Segmented Sieve - Efficient method to find primes within a given range

### ISSUE THREAD

**Issue by Shadow-Master-007** [topcoder-platform/thrive-submit#232]
Track Category: Competitive Programming
[Segmented Sieve - Efficient method to find primes within a given range.docx](https://github.com/topcoder-platform/thrive-submit/files/4013650/Segmented.Sieve.-.Efficient.method.to.find.primes.within.a.given.range.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by harshitmehta123** [comment]
We already have an article on Topcoder around this. https://www.topcoder.com/community/competitive-programming/tutorials/mathematics-for-topcoders/
Written in a very similar fashion as you have.
Sorry!

**Comment by harshitmehta123** [comment]
Would suggest you to publish this on your medium blog and if you have any new topics you want to pen articles on. Reach out to us at thrive@topcoder.com

**Comment by Shadow-Master-007** [comment]
https://www.topcoder.com/community/competitive-programming/tutorials/mathematics-for-topcoders/

This link contains methods to check whether a given number is prime or not and finding primes in a range (Sieve of Eratosthenes). But I posted this article because there is another advanced (or say generalized method to the sieve method called the segmented sieve) which is **not present on the topcoder platform** (either in the form of a post, article or in the thrive).

I mentioned the naive sieve method (which has been already described in the link provided), so that people can easily relate to it and switch and learn the advanced segmented sieve method easily (naive sieve of eratosthenes method is a prerequisite for learning segmented sieve - that's the reason I wrote it in my article, despite being already present on the topcoder platform). Now refering to the basics to switch and make people learn advanced topics doesn't mean that the article is similar.

I request you to consider it for **thrive** (as it is **not present** on the **topcoder platform**) and it can be of **great help for problem solving and competitive coding enthusiasts** who look for **quality resources on topcoder** to learn and achieve new things.

**Comment by Shadow-Master-007** [comment]
> https://www.topcoder.com/community/competitive-programming/tutorials/mathematics-for-topcoders/
> 
> This link contains methods to check whether a given number is prime or not and finding primes in a range (Sieve of Eratosthenes). But I posted this article because there is another advanced (or say generalized method to the sieve method called the segmented sieve) which is **not present on the topcoder platform** (either in the form of a post, article or in the thrive).
> 
> I mentioned the naive sieve method (which has been already described in the link provided), so that people can easily relate to it and switch and learn the advanced segmented sieve method easily (naive sieve of eratosthenes method is a prerequisite for learning segmented sieve - that's the reason I wrote it in my article, despite being already present on the topcoder platform). Now refering to the basics to switch and make people learn advanced topics doesn't mean that the article is similar.
> 
> I request you to consider it for **thrive** (as it is **not present** on the **topcoder platform**) and it can be of **great help for problem solving and competitive coding enthusiasts** who look for **quality resources on topcoder** to learn and achieve new things.

**Comment by harshitmehta123** [comment]
How about we work on improving the already existing article on sieve and adding to it? I will reach out to you to help in improving and adding to it. Drop me an email at harshit@topcoder.com if you are interested :)
