### ISSUE TITLE
Color Theory In Graphic Design

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#24]
This is my article, please check and give me feedback ..

[Color Theory In Graphic Design (Wildan Abdul Azis).zip](https://github.com/topcoder-platform/thrive-submit/files/3926761/Color.Theory.In.Graphic.Design.Wildan.Abdul.Azis.zip)

**Comment by kkartunov** [comment]
@KakaIdan it needs to pass Plagiarism Check https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYBCUDOAlhAAoCuAdhDGADRgIpJkAOWY5VMZshSFdSLESo0ACTIBbKAOwBhJJOkACALKF8ZfHGUB3QjAAWhCsrkAbKFrj5BEZhRqYAbAF9a4aPGTp2CySyc1IKMzGzYQdy8-HbCPuJSMuyRPDB8piZmiiwOACYA9P4s5nAAHsoAynCO1RA2dg5Obh5C3qLsAGIoUAiS1TT0oazsVTVUcBUwKGTUZChwsW3oEtKyYACSVNkl8JX9tfX09pROAIzunnHtEQREAG5wAGpIxAuDTMPYk2gliyLLiTWJFuhAeymerzUGmsDROWAAnBdWv8MNh1Ph8Cw4OYSrkQh9wmAKlicSYEH94iskmiNJjsbjlAB1VC5WxHRpYABMSK8KPYzJQuRMNjZDAJIxgPzeyMpgP5LLQezGdVFx0cXJ5V18EUsCEIUBQGkk%2BLCyV1%2BsN%2BGNRy1CVW7AAqhRUIQ9RQoOZlPYxgNIBzMNyWrz4sl5jkiGl%2BKKhoSAOLdJQGimiKlrRlMCgIZSoKEYsnKEhhpAR9Kq-3nIO2zqoaQwNKZk2fImS342pZ26kbAJMLEoZQdGuwevk9lwgOa9vywVyQwvOqNwkAUQohhkdT66rbKNTU9yZlnr1h6swAGYJ3zsALcgB5QVwFALkb7caTaazebJgH2mmYyx1PdXvg2Z9iQhjdNoZZjucAC6QA&page=plagiarism&breadcrumbs=true

**Comment by KakaIdan** [comment]
Other than that, is there another evaluation?

**Comment by KakaIdan** [comment]
Hi good morning ..

Please check the results that I have corrected. Thank you ..

[Color Theory In Graphic Design (Wildan Abdul Azis).docx](https://github.com/topcoder-platform/thrive-submit/files/3928882/Color.Theory.In.Graphic.Design.Wildan.Abdul.Azis.docx)

**Comment by kkartunov** [comment]
Passed Plagiarism Check

**Comment by Dara-K** [comment]
Hi! We already have 2 large articles on the blog that cover the topic of Color Theory extensively so many of the points highlighted by you can be found in these articles:
https://www.topcoder.com/understanding-color-ui-design/
https://www.topcoder.com/the-world-colors-and-how-to-conquer-it/

Please double check the articles we have before adding new ones on same/similar topic.
