### ISSUE TITLE
An Introduction to SymPy

### ISSUE THREAD

**Issue by jlhopkins28160** [topcoder-platform/thrive-submit#249]
Track: Development
Author; hopkins28160

[An Introduction to SymPy.docx](https://github.com/topcoder-platform/thrive-submit/files/4294055/An.Introduction.to.SymPy.docx)

**Comment by kkartunov** [comment]
passed min checks

**Comment by billsedison** [comment]
Looks okay to me, but it is more related Data Science track. @kkartunov 

@harshitmehta123 Maybe you want to have a look?

**Comment by billsedison** [comment]
Discussed with @harshitmehta123, the article is not that helpful, the main resources can be found from https://docs.sympy.org/latest/tutorial/index.html. People is better to get started by the official tutorial.

So we have to decline your article. Thanks for your efforts anyway.
