### ISSUE TITLE
Add Google Map in Flutter And Get Users current Location

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/thrive-submit#255]
[Flutter Article Thrive.docx](https://github.com/topcoder-platform/thrive-submit/files/4402936/Flutter.Article.Thrive.docx)

Track - Development

**Comment by kkartunov** [comment]
passed min checks

**Comment by kkartunov** [comment]
@billsedison, please review.

**Comment by billsedison** [comment]
Good article. However, in the article https://github.com/topcoder-platform/thrive-submit/issues/252, it already contains the code about how to get the current location. So we can't accept the article that has the similar content. Sorry.

**Comment by rajanmourya** [comment]
Ok, No Problem
