### ISSUE TITLE
Learn How to Parse Complex JSON in Flutter for Beginners

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/thrive-submit#258]

**Comment by rajanmourya** [comment]
[Json Parsing.docx](https://github.com/topcoder-platform/thrive-submit/files/4461811/Json.Parsing.docx)

Track - Development
Topcoder handle - rajanmourya2015

**Comment by kkartunov** [comment]
ready for review

**Comment by kkartunov** [comment]
@billsedison can you please review this one?

**Comment by billsedison** [comment]
Sorry for the late response. The article is generally simple and the content has no essential difference with the official tutorial. https://flutter.dev/docs/cookbook/networking/fetch-data

We are looking for an article for more advanced content. Sorry, we can't accept this article.

**Comment by kkartunov** [comment]
Thank you @billsedison and @rajanmourya 
@rajanmourya you can try other topics and dive deeper in them...
