### ISSUE TITLE
Migrating Db2 to Db2 12 in ZOS-Mainframe Environment/Unix

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#26]
[db211_db212_migration_zos.docx](https://github.com/topcoder-platform/thrive-submit/files/3927372/db211_db212_migration_zos.docx)

**Comment by kkartunov** [comment]
Passed Plagiarism Check

**Comment by kkartunov** [comment]
passed min length check

**Comment by billsedison** [comment]
It's from https://www.ibm.com/support/knowledgecenter/beta/en/SSEPEK_11.0.0/inst/src/tpc/db2z_migrdb2.html
