### ISSUE TITLE
Hypothesis Testing

### ISSUE THREAD

**Issue by jlhopkins28160** [topcoder-platform/thrive-submit#268]
Track: Data Science
Handle: hopkins28160

[Hypothesis Testing.docx](https://github.com/topcoder-platform/thrive-submit/files/4471747/Hypothesis.Testing.docx)

**Comment by kkartunov** [comment]
@jlhopkins28160 https://www.grammarly.com/plagiarism-checker detects plagiarism on this one. Please, fix.

**Comment by jlhopkins28160** [comment]
I checked Grammarly and it did not detect plagarism.

**Comment by jlhopkins28160** [comment]
I checked my document again and Grammarly did not detect plagiarism:

![Topcoder_Post](https://user-images.githubusercontent.com/498140/79268934-91bd7580-7e69-11ea-8f8c-20551d9abbf8.JPG)

**Comment by kkartunov** [comment]
@jlhopkins28160 I can't confirm that. I see it detects.
![Screenshot from 2020-04-15 10-07-52](https://user-images.githubusercontent.com/5585002/79308343-17403480-7f01-11ea-8796-5f0609d7b72c.png)

Link: https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYDCSC2ADgAoCuAdhDGADRgIpKmFZhmUymwCWS5tkWIlRoAEqXxR%2B2dlS4xe5AATdleIk3IATAPTrCAGzgAPJQGU45eJTgBnARE3VMARgC%2BNcNHjJ0rYlC2ttwAbnAAakjcEHACDEws2GYwaEYOQr5iElL%2BgcFhSpHRcEoAsty2pLaxdI4UzgDMHl4ZIqwA6qhaqnb2dPHMrMmpNYI%2BIuKS0mCdKFpo5pbWMX2QTlhNnmPCfjIocIRIwQp8qwOJYADiKFD4kijp4%2BiTOdjtjOQISqhlFcGfSmI%2B0Ox0UqzqViwACZmttMv4DFAENwoCgKvg4oxBjJEcjUejHjsslNWABVciobjI8hQAxKRxWJYOdauAAMsO8RNYADFUJIYApPpiEkMUmlaq1ntlpgBJIiMQhwFBKXkofmChDM%2BpYdxbTnwt5dHAACyiMWF2LAAFFyMapDF8EyJU9ia8Zl0lCazaMIc4XDC9ZKMNg8NpuCcaQYLRdrrd7oTMi9pqHuhHaYtGTZwSzdS0XawcIi0Slo6KRgmJtLWDKrGjOUoAComai1HMcoP%2BD6aM5YmM3O6oitSkl7PiaJSk6payGuNwAXSAA&page=plagiarism&breadcrumbs=true

**Comment by jlhopkins28160** [comment]
@kkartunov I have corrected the document and there should be no issues with plagiarism

Track: Data Science
Handle: hopkins28160
[Hypothesis Testing.edited.docx](https://github.com/topcoder-platform/thrive-submit/files/4488527/Hypothesis.Testing.edited.docx)

**Comment by kkartunov** [comment]
@jlhopkins28160 article should be more than 500 words long. Yours is 487 words.
I am also getting "Plagiarism was detected!" error still.

Considering the above I am closing this one. Please, prepared better articles and submit them again. Thank You for your efforts.
