### ISSUE TITLE
AWS Cost_reduction_process

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#27]
[aws_cost_reduction_process.docx](https://github.com/topcoder-platform/thrive-submit/files/3927388/aws_cost_reduction_process.docx)

**Comment by kkartunov** [comment]
@t0070926 please stop opening issues for the same articles! We can handle everything in one issue and do not need 10ens of those.

**Comment by t0070926** [comment]
Both are same by mistake i closed .Its passed the Passed Plagiarism Check.Please consider this for review

**Comment by billsedison** [comment]
@t0070926 

Thanks for your article, but I have two questions:

1. You proposed a cost reduction at the python language level, but how can I apply it if I use NodeJS, Java or other languages?
2. At the AWS Cloud level, what's the difference between the official AWS Cost optimization https://aws.amazon.com/pricing/cost-optimization/?nc1=h_ls

**Comment by t0070926** [comment]
1.Applying  same  multi threading  concept in other  languages  even java c++ supports this feature. 
 Concept is effective utlization of CPU time and improve the performance of the job
2.Cost optimization aws provided some conepts of how to use their resources effectively and i have added some additional points like when huge data need do the partitioning the table space and table level

**Comment by billsedison** [comment]
@t0070926 Sorry, I don't think it's helpful.

1. The multi-threading concept has many side effects, like data race etc, might cause additional issues.
2. Python generator is not a multi-threading concept, it's more like coroutine, but it cannot be applied to multiple languages.
3. For the cost optimization, most of the contents are overlapped with the official AWS content.

So I cannot accept this document. Sorry.
