### ISSUE TITLE
PartitioningDB2for zOS-tablespaces

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#28]
[PartitioningDB2for zOS-tablespaces.docx](https://github.com/topcoder-platform/thrive-submit/files/3927616/PartitioningDB2for.zOS-tablespaces.docx)

**Comment by kkartunov** [comment]
Passed Plagiarism Check

**Comment by billsedison** [comment]
The format is bad and the sentence looks not fluent.

Is it picked from some book?

You mentioned Figure 3, where it is? Where is figure 1 and 2?

![image](https://user-images.githubusercontent.com/5657467/70877762-bc054080-1ff9-11ea-9b08-b1d19c79ae28.png)

Sorry I can't accept this article.
