### ISSUE TITLE
The Easiest Way to Choose a Color Scheme for UI Design

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#283]
Track Category: Design

Google docs link for this article

https://docs.google.com/document/d/1KbCsPoc3RdWTbIl3eXyHsSMkzC_ceOufzF6v2ZTZBEU/edit?usp=sharing

**Comment by kkartunov** [comment]
passed min checks

**Comment by fajarmln** [comment]
@hasanozie I've checked the article and it needs more background knowledge/basic theory about colors, it cannot be instant method.

**Comment by hasanozie** [comment]
Hi bang @fajarmln 
I have updated this article by adding color functions to the UI design and some techniques for creating Color Schemes.

https://docs.google.com/document/d/1KbCsPoc3RdWTbIl3eXyHsSMkzC_ceOufzF6v2ZTZBEU/edit?usp=sharing

**Comment by hokienick** [comment]
We will pick back up operations of Thrive articles in July.

**Comment by harshitmehta15** [comment]
Hey @fajarmln - can you do a quick check on the updated article? :)

**Comment by fajarmln** [comment]
Will check shortly @harshitmehta15

**Comment by fajarmln** [comment]
I cannot pass this article, the content 'still' mostly about instant knowledge about colors and not suitable for THRIVE article
