### ISSUE TITLE
Adversarial Autoencoders: Deep Learning Applications in Drug discovery

### ISSUE THREAD

**Issue by tapishr** [topcoder-platform/thrive-submit#284]
Track: Data Science
Author: Tapish.Rathore

https://docs.google.com/document/d/1wMFKQ3-q3EVvbhJ33h3iOuZzjyeejtxFaBCHyctwIgo/edit?usp=sharing

**Comment by hokienick** [comment]
We will pick back up operations of Thrive articles in July.

**Comment by kkartunov** [comment]
passed min checks.

**Comment by harshitmehta15** [comment]
Hey, @tapishr Sorry for the delay in reviewing the article. Would you like to add about a few projects Topcoder has done in Data Discovery and some words around how deep learning would have shaped those projects like: EPA ToxCast, Pfizer GWASS, or Harvard Precision Med.

Let me know if you are not able to locate details about these Topcoder Competitions.

**Comment by harshitmehta15** [comment]
Hey @tapishr - Will reject this for now. If you plan to work on it with the improvements suggested - please submit again and we would be happy to publish!
