### ISSUE TITLE
EdgeX Foundry - Why it is important for anyone creating edge applications/solutions

### ISSUE THREAD

**Issue by CamiloDennis** [topcoder-platform/thrive-submit#285]
Title: EdgeX Foundry - Why it is important for anyone creating edge applications/solutions
Authors: 
Jim White: IOTech’s CTO and co-chair, EdgeX Foundry Technical Steering Committee 
Camilo Dennis (TC Handle: CADEdgeXTC-20): Intel’s IoT Marketing Manager and chair, EdgeX Foundry Marketing Team
Track category: Topcoder - Development

[EdgeX Foundry - Thrive Article 6.2.20.docx](https://github.com/topcoder-platform/thrive-submit/files/4718288/EdgeX.Foundry.-.Thrive.Article.6.2.20.docx)

**Comment by kkartunov** [comment]
[Plagiarism detected](https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYDCSC2ADgAoCuAdhDGADRgIpKmFZhmUymwCWS5tkWIlRoAEqXxR%2B2dlS4xe5AATdleIk3IATAPTrCAGzgAPJQGU45eJTgBnARE3VMAVgC%2BNcNHjJ0rACJw8Cj4qnAo9nQMTCzYAOIoUPiSKA5CvmISUgFB4aHk4UoAqrZwSgAUUDpSOjAAFnC1ddy2NEpBEAB0AJQOTlgATB5e6SKsxFC2ttwAbnAAakjcEHAC0cysZjBoRmk%2BIuKS0myT03NKi8tlALItpKV9FM4ALMOC%2B34yBlAI3FAoLXwa0YGy%2BPz%2BANsQLo3mE6EO2WwRXIqG4v3IUAMSkcVks1Bh-UwQ087zhGBkKDghCQ0wUfEi9BBsTACSSKT2ZIRxwA6oxyAglKglLcpqoBcRKdTaYoGY4nlgAIxvWEZVh4AwGJAAR1IfwMwJim22uxho3hWWOAEkMYRCIw7X94Ep1ZqdXrAbLCUqSSqxtgcN8AdsDaCwFsdqtTR9MkdWNaYADYUoAComfGQL3Ks3kth8zQM9bM1nJf4cjJc8Z5ijFB4E%2BWYb0jaOsABCk2WsnThfGFDkPD4ZYOFrVBEkwrupSUAHduPVVM7vvc7I8rFgAMxZ5tI8gAaxRU-4USZm0IcA1YsH5tj273SAPSm5qC0nvrxKbZNYItsp41cC0IeZMwfwMC8o05YdsC-YC-wfJ8X1XTAADZNw-bAgLgCA9RwOp-igKhwgLY8ZF7Th%2B0PUlywgsARSXQUADNzDgUJHE1chWiUABFUgkBgMjhX%2BHd2I6ToV2cRsKL9MBHxQLRsKWFYANYABRcgcJsfA8UvGNESkp9nTqeTIwzetXgAXSAA&page=plagiarism&breadcrumbs=true). Please fix to continue.

**Comment by kkartunov** [comment]
@CamiloDennis are you going to submit update for this one?
