### ISSUE TITLE
MARATHON LOCAL TESTER PARAMETERS

### ISSUE THREAD

**Issue by harshitmehta15** [topcoder-platform/thrive-submit#288]
https://docs.google.com/document/d/100JX1dgENRlrxt3tZfVWQ70PxoOQjyl1LfxlvnWxRG8/edit
Title: MARATHON LOCAL TESTER PARAMETERS
Author: Wladimir Leite / wleite
Track Category: Competitive Programming
Subcategory: Marathon
Tag: How-To

**Comment by harshitmehta15** [comment]
Hey @kkartunov can you help me publish this?

**Comment by kkartunov** [comment]
Done
