### ISSUE TITLE
An Introduction to pandas-profiling

### ISSUE THREAD

**Issue by jlhopkins28160** [topcoder-platform/thrive-submit#290]
Title: An Introduction to pandas-profiling
Track: Data Science
User: hopkins28160

[Pandas-Profiling.docx](https://github.com/topcoder-platform/thrive-submit/files/4843626/Pandas-Profiling.docx)

**Comment by kkartunov** [comment]
Passed checks

**Comment by harshitmehta15** [comment]
Hey @jlhopkins28160 Nice Article. Can you add some preview images of the report generated?

**Comment by harshitmehta15** [comment]
Hey @jlhopkins28160  - rejecting this for now. Incase you are able to add some preview images - please re submit! :)
