### ISSUE TITLE
Cypress vs Selenium [WIP]

### ISSUE THREAD

**Issue by VanitaW** [topcoder-platform/thrive-submit#299]
Hi,

I want to do a series of testing articles.  One of the articles is listed in the sample topics.

1. An introduction to automated testing - Selenium's beginner's guide.
2. Cypress vs Selenium
3.  Automated testing - Test Coverage. In this article, I will explain the different types of coverage, how to calculate the coverage, how to take the edge cases into account and how to optimize test coverage to achieve at lease 90 percent coverage.  I will use Selenium and Java.

**Comment by harshitmehta15** [comment]
Hey @VanitaW thanks for writing articles for Topcoder Thrive!

- **An introduction to automated testing - Selenium's beginner's guide**. - is actually a very common article. I think you can do an advance level and look for another interesting topic here
- Cypress vs Selenium This is a nice article - we can start with this. What are you planning to include in this?
- Automated testing - Test Coverage - This is great - you can start with this too :)

**Comment by harshitmehta15** [comment]
Each issue has to be an article - so make sure you edit this issue to the one you are planning to work on first and submit the doc here :)

**Comment by VanitaW** [comment]
Thank you!  I will edit this issue and submit the articles soon.

**Comment by kkartunov** [comment]
@VanitaW do you plan to finish this one?

**Comment by VanitaW** [comment]
@kkartunov Yes, I do plan to finish this article and submit another one soon.  Tuesdays, Thursdays and Saturdays are my writing days.

**Comment by kkartunov** [comment]
closing due inactivity.
