### ISSUE TITLE
Handle text data using NLTK

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/thrive-submit#306]
Category: Data Science
Author: Anurag Sharma

[nltk_basics.md.zip](https://github.com/topcoder-platform/thrive-submit/files/5631557/nltk_basics.md.zip)

**Comment by kkartunov** [comment]
passed min checks

**Comment by harshitmehta15** [comment]
Hey @anu0012 - This is a very basic topic and a lot of content is readily easily available on the internet. Unfortunately will have to reject this one.
