### ISSUE TITLE
Understanding Random Forest and Hyper Parameter tuning

### ISSUE THREAD

**Issue by tarushi96** [topcoder-platform/thrive-submit#311]
Track: Understanding Random Forest and Hyper Parameter tuning
Author: Tarushi Gupta
[tarushi_pysark_article2.docx](https://github.com/topcoder-platform/thrive-submit/files/5640629/tarushi_pysark_article2.docx)

**Comment by kkartunov** [comment]
@tarushi96 thanks for the article. Unfortunately, it fails Plagiarism check https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYDCSC2ADgAoCuAdhDGADRgIpKmFZhmUymwCWS5tkWIlRoAEqXxR%2B2dlS4xe5AATdlEAoSbkAJgHp1RADZwAHkoDOccvEpxzA9RWqYAbAF8a4aPGTpWAETh4FHxVOBR7OgYmFmwAcRQofEkUByFfMQkpAKDw0PJwpVJLJQAKKF0pXRgACzhqmu5zGiUgiAA6AEoHLWcARj6PL3SRVgAlOChtKAAjbkNuGAwoxmZWAGUl4zSfEXFJaTBRKBRtAFoYJDOUSe0leBNqOkdrLEHPQV2-GShzc24AG5wABqSG4EDgAmia2wmzQ22eI3Q%2B2yPz%2BgLgSgBYIhSlC5mKkOevSwAHYhp9hN8wP5uFBjFRIvRVrEwOtCHBDAtyAgdlTMgdWABZbgmOB3bR0hkwcxKJAAMyUAFEeQtzDUek43hTvPzWHguUgAI6kKVQlkbLZEykZFGHACS5CghEIjFddPgSnUhpNUqa%2BCZL2cACYdUiMDJDFAEHSUP7zTFWMQozGTvHEV8BaiwABVciobgxp2GL18GxPSAkzAAZjDmdYACFfuDZBXoazW-JFHzbVlDnhklA8U1CUoAO6LRpqKOEwNV0MfXUZVh5gDW%2BbH-BWidhHK5ql5Gf5dpX5HXSE349Q2jnWsw72G9ewIr%2Be%2BM2gTMLZb4PPb2feFJpzDfcUr1OW9XhrOs9WwAB1a8wj%2BT9WThBEbX-QU4OvNALCsGwIQg-poOXbAAEEIAgbhtDw%2BlDDQPByHlQkP23L92U5blD3Q5EAOwBimMsO4x2vQisHcRdw1YeDThwGocWtdtWBVGopAhfA8L-HjMLAaS7ggOTwWtIMsAAFmI0ZYWBUjkNYBIkhSTSs0OAAxKBSEMJYLFIGYACs4CoM4gRQGYlGjG44HU15iTvQYAF0gA&page=plagiarism&breadcrumbs=true

Please update and resubmit.

**Comment by tarushi96** [comment]
It doesn't show when I submit it, it is not copied.

https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYBCUDOAlhAAoCuAdhDGADRgIpJkAOWY5VMZshSFdSLESo0ACTIBbKAOwBhJJOkACSYXxl8cZQHdCMABaEKyiABsomuPkERmFGpgBMAX1rho8ZOnYAROPAoahRwKDb0jMxs2ADiKFBKUCi2wt7iUjJ%2BAaHBocpWygAUUAD0MiWGcBVG%2BLTKARAAdACUtvaOAIyu7kJeouwKkiyc1IKRrOwj3Lz8KX3oEtKyHJTUPDB8Jsamiiz2ACYldkNmcAAeyloOcFTWbZSOAOxuHqn92ABKcFD7UABGhDM%2BgwESYE2wAGUYGhTnMRAsMssxEl9gBaGBIVEob77ZTwM40eh2B5YDovXrwjDYEgEIgANzgADUkMQ4GMwdEwFCYWyiW8EUtJrTCAzlHSWRBtGoNFp7g4sAA2cmeSnsACy6nwLDgZlO%2B3ZUXYEO1uuMCDhaUWmWwGvwWp1et0qH24Ug7Sw3Ve8ypYF8hCgp2orvGnONDrNFtEVuWGrOcFx%2B39gZg%2BGUSAAZsoAKIUBBA-AGOWdZX8n0KXVIACOZCTBvBXOhsL53uj7AAkhQoCwWEwe-74DsK9Wk%2BpJK7ifLnCXvewAIIQCCEfY3GABsxoBQUdNWfWgw2Qk1A3ORgXWsCb7daXE6Z3j92YACs09V1IsCH9KFHdc5JDfH6-zaUq22AAKoUKghDvp2Zg7Nc8pEveZI9CqaTsAA6s6cgGBKvIMBy7A5gYMiSpIK4nukgrYBhKC4hA2GskWWAAMzPqhkKMrO37sHECTSMkgGWoi7AAGKWGY0KXGQfwAFZwNQqIMigfzKFAjBwHApHwW6JKYGSAC6QA&page=plagiarism&breadcrumbs=true

[tarushi_pysark_article2.docx](https://github.com/topcoder-platform/thrive-submit/files/5641826/tarushi_pysark_article2.docx)
