### ISSUE TITLE
 Important tools used  to ease communication by Topcoders’ remotely

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#313]
Category: Topcoder
Author: Rokit12

Here is the document link:https://docs.google.com/document/d/1bkAtrpHdds8fnsVccADdD0G3GSqdj-ECDws_TRp29us/edit?usp=sharing

**Comment by kkartunov** [comment]
@Rokit12 thanks for your article. Unfortunately, there is much information of the same kind on Thrive and all other Topcoder sites. People will know to find communication following official channels.
