### ISSUE TITLE
Introduction To JUnit

### ISSUE THREAD

**Issue by nursoltan-s** [topcoder-platform/thrive-submit#319]
[Testing in Java.docx](https://github.com/topcoder-platform/thrive-submit/files/5647087/Testing.in.Java.docx)
![Screenshot](https://user-images.githubusercontent.com/7783676/101243867-09644b80-373e-11eb-801b-9d057276ee9c.png)

**Comment by kkartunov** [comment]
@nursoltan-s plase update your article to pass the Plagiarism checker https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYDCSC2ADgAoCuAdhDGADRgIpKmFZhmUymwCWS5tkWIlRoAEqXxR%2B2dlS4xe5AATdlEAoSbkAJgHp1RADZwAHkoDOccvEpxzA9RWqYATAF8a4aPGTpWxKHNzbgA3OAA1JG4IOAEGJhZsAGUYNGMHIV8xCSl-QOCwpRComKV8bnNSSwctZwBGDy9MkX9DKARuKBQK-DjGZlb2zu7zXrpvYXRxSWkwAFVyVG4O8ihDJXVrK2px2qwAVkbBHxaZFDhNYIU%2Bezp4gewAcRQofEkUDJOpnNmAdUZyAglKgyhVgoClIRzpduNdyLdIHtMA1PMdJhhkoQ4BBOoYcAALLpQKhwFAI%2B6JNgUOQ8PifdHTXLYACyFSqcGBADMLHByupDDcaEoAI6kJAwWnKd4Aa3MQrgMAgADoak4sO5URMsqxfqhtASSrE7v1KQBRciE2z4bb0rKMv56jb4w2q6xYADsRy1p1wbW6qT6CVYKTSRrRdp%2BrAAktZuhMlPATDtEWrkW4ALpAA&page=plagiarism&breadcrumbs=true

**Comment by kkartunov** [comment]
Closing due inactivity.
