### ISSUE TITLE
How to calculate median, standard deviation of a column in PySpark data frame

### ISSUE THREAD

**Issue by tarushi96** [topcoder-platform/thrive-submit#326]
Title:  How to calculate median, standard deviation of a column in PySpark data frame
Category: PySpark
Author: Tarushi Gupta / tarushi.gupta
[tarushi_pysark_article_PySpark2.docx](https://github.com/topcoder-platform/thrive-submit/files/5654788/tarushi_pysark_article_PySpark2.docx)

**Comment by kkartunov** [comment]
Passed min checks.

**Comment by shubham9455999082** [comment]
without banner image

**Comment by tarushi96** [comment]
https://cdn.datafloq.com/cache/blog_pictures/878x531/machine-learning-solving-user-authentication-apps.jpg

There is link to this image

**Comment by tarushi96** [comment]
? @kkartunov

**Comment by harshitmehta15** [comment]
Hey @tarushi96  - this is very basic and is easily available on the internet. Please resubmit incase you are planning to better it  :)
