### ISSUE TITLE
Double post

### ISSUE THREAD

**Issue by kreasindo513** [topcoder-platform/thrive-submit#338]
Sorry, Double post

**Comment by kkartunov** [comment]
@kreasindo513 it fails the test https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYAid4oC2AlgHZwoDOYANGAikgK4AOWYA4ilIYVCrUixEqNAAkmfUuzwES5FAAImlOIoAUUAPRRSWmAAs4%2Bg8Uo1F%2BCADoAlIIjNSMLACYAvjXDR4ydOwBhJEIWAAUmUggXOgZmNmxwyJgmWGIkaTofEXQJKXZEqJSYNNJFMkVHEKcAEy1KlgAbOAAPRVVnOEi4akynF0wARk9vYT8MbAAxbgRCTuj6RlZ2AGU5zog4ZZgUJkKUOAdR0VzddgBJSODG-DV2%2BC6eyD6sIa8hX1F8qEpKYgA3OAANSQxA2gliS2wWzQTUOHxyklOCW%2BvwBij%2BII2ihIlBUB16EX6ABZhu9suMwAB1VDVMjdR4Q%2BJgaGwzJHBF5bDUlDVNBtNYPBzPQakrJjfINKAIYj8MyEcGLJmhSXS2WUeVs%2BHiRHSbAAVVIqGI0tIUAaFXS93mjkJWAAzKL2RTudUAgZMfiFnF2ABRUgGXQbWbOOHkk66qk0iru0Gem0hzAANkdWsCkpQxBgGBiipWWdZZLG4fOzgzWUU8Ga1uFrxGqYSjENEQZuewXB4fAEmrDOvyjacylUQttIoAukA&page=plagiarism&breadcrumbs=true

**Comment by kreasindo513** [comment]
Sorry, Double post with previous article.
