### ISSUE TITLE
How to Troubleshoot IMS DB Online Transaction Issues

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#34]
[How to Troubleshoot IMS Online Transaction Issues.docx](https://github.com/topcoder-platform/thrive-submit/files/3930810/How.to.Troubleshoot.IMS.Online.Transaction.Issues.docx)

**Comment by kkartunov** [comment]
passed Pcheck

**Comment by billsedison** [comment]
@t0070926 

Can you please format the document well? It's a bit difficult to read.

For example, 

this should be a table.
![image](https://user-images.githubusercontent.com/5657467/70441472-6bf51e00-1acf-11ea-9cd6-615ba1288e9b.png)

the code/command/console text should be in a different font.

![image](https://user-images.githubusercontent.com/5657467/70441512-7fa08480-1acf-11ea-8668-a35c3100bcaa.png)

**Comment by t0070926** [comment]
[troubleshoot_IMS_Online_Transaction_Issues.docx](https://github.com/topcoder-platform/thrive-submit/files/3943303/troubleshoot_IMS_Online_Transaction_Issues.docx)

**Comment by t0070926** [comment]
I have updated  details.That is not table.Its Mainframe job.When IMS db on line trasaction fails abend status can see in the jobformat.I have provided in screen shot format.Its mainframe environement and particularly IMS very few sme's avilable in this area.This is informing you because you are not from Mainframe back ground

**Comment by billsedison** [comment]
No, you should not just make them as screenshots. We cannot accept this. Sorry.
