### ISSUE TITLE
What are the new features in Python3.9

### ISSUE THREAD

**Issue by balavenkatesh3322** [topcoder-platform/thrive-submit#348]
Title: What are the new features in Python3.9?
Author: Bala Venkatesh
Track Category: Software development
Subcategory: Theory
Tag: Python3, Web apps

User name :- balavenkatesh.s
mailid :- venkateshpnk22@gmail.com

[Blog link](https://docs.google.com/document/d/1R6MaZzHZGGwVLfx0D4irSbA3xfMDmatZ3H1F20RcjAs/edit?usp=sharing)

**Comment by kkartunov** [comment]
@balavenkatesh3322 it fails the tests:
https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYDCSC2ADgAoCuAdhDGADRgIpKmFZhmUymwCWS5tkWIlRoAEqXxR%2B2dlS4xe5AATdlEAoSbkAJgHp1RADZwAHkoDOccvEpxzA9RWqYALAF8a4aPGTpWAETh4FHxVOBR7OgYmFmwAcRQofEkUByFfMQkpAKDw0PJwpVJLJQAKKF0pXRgACzhqmu5zGiUgiAA6AEoHLWcAVg8vdJFWYihzc24ANzgANSRuCDgBaOZWAGUYNGM0nxFxSWk2ccmZpSmFpaVQ82LlukdrLAAmQcE9v2xZ8IAjSPpGGt4olklBUg9hugDtlsABJSioFBwKjnX5KABmqHw-0ezgAjG9vMJPmB-NwoMYqP9VrEwOtCHBDIZVAhdsTModWABZbgmODaJTacmUmDmJRIdFKACi5AQzPMNR6ThehMhGBkhigCHJKCa%2BBWgNpxE12rBerZGWhRwAquRUNxteQKUp1NYrNQHr0sHiAAyqj7qsAAMSxsAUsoNMQ2Wx2EIDVtYsKIjAZKAxoZg4dZnuVmDxBM873ZrBwmt1W0jQLpMfuRctWSO8JguqJSngJg9kC9ef9xewACFxotZJ2aaMKHIeHwLfsGyWCJJrk07koAO7cWqqF2au447sFoYB1i2gDWdtX-Ciho2DKZLJnULn2FP5%2BUq9Q2j3uYPdZG2CDiQIPg7qVrS6zulYSybCgpByEiD4cjCYDwgYhDGPAFgQbYX5PD2hZEhk3JNOYt7GNooE3oyzIRnG7IJtgPITKR-Jrh%2BOH4n6%2BFqqwAByWjUtewJJCkCH0chCIoEiKJ2hQSjkBIPzhEquE-gRf5gAA6h%2BYQTBR2CbNstZqY%2BnLYFpKDaGgmFuthynOK8XFHtgACCEAQNw2juhShhoHg5Donc5FXlG%2BmkfetH1qZuB8AFlgCu%2BFnsd6vaEWZH44DUly1mO2AyjUUhLMBTwRbOUXmQKECZYsRndgAzCl6nrLMzl6WACTCWColPsGUCkIYWwWKQPwAFbIjAAC0MwoD8ShakicBFZ2uLJQAukAA&page=plagiarism&breadcrumbs=true

**Comment by balavenkatesh3322** [comment]
@kkartunov  I have fixed that issues


 https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYDCSC2ADgAoCuAdhDGADRgIpKmFZhmUymwCWS5tkWIlRoAEqXxR%2B2dlS4xe5AATdlEAoSbkAJgHp1RADZwAHkoDOccvEpxzA9RWqYArAF8a4aPGTpWAETh4FHxVOBR7OgYmFmwAcRQofEkUByFfMQkpAKDw0PJwpVJLJQAKKF0pXRgACzhqmu5zGiUgiAA6AEoHLWd3T0EfEVZiKHNzbgA3OAA1JG4IOAFo5lYAZRg0YzSh9HFJaTYxiemlSfnFpVDzYqW6R2ssACYPL3Th7H9uKGMqSPpGKtsGtCHBDIZVAgdsI9llDgBZbgmODaJTab6-GDmJRIABmSgAouQEBDzDUek5nq9BjCMNgZuEAEb-FaxMAJJIpaEZfbZbAASUoqBQcCoZyZSlxqHw-wezgAjNTvLSRoYoAhvigmvhloC2cQ1RqoFrzDr7u9YQdWABVciobga8g-JTqaxWaj3XpYRUDZUZVgAMWlsAUxN1MXWm225t2mStAqIjFBKElwZgoahnspmHlL19FrpuDVWs24aBYA2WzuNJ5cNYgpgWuVSngJg9kC9OaVBdYACExgtZO3WSMKHIeHxuSJeYc8MkoFcmrclAB3bi1VQutW3WWdn1vWM28gAaztK-4UT161B4MhU8tfLAttPSHPq9Q2l32f3NY%2BYADiQIPg7plmyazulYiwbCgpByCK95xo%2BgoGIQxjwBYEG2F%2Bjxdvmh7YIi4w3sY2igdeYIQmGMa0jOrCEeYxEou%2BKCfhSOHygADN2%2BFgAA6h%2BYTjGRwJRtWfrTnW2D8SxaAYW6WFsc4eYHiq2AAHJaCyV7xIk86pNRtbxmAyHCqKMBKHaFAWRIjLhIp3rcapYAAIIQBA3DaO6PyGGgeDkLitykZeEbAsRd4GRJRl%2BQFlioiuH7YQqjn%2BlJH44DUFzViO2BEjUUiLMBjwRQ%2BhzSaiEAZQsYmdgALMlf5rDMznCeyulcsViGHAGUCkIYmwWKQjIAFZmQAtNMKCMko6oinAhXtnKDkALpAA&page=plagiarism&breadcrumbs=true

**Comment by kkartunov** [comment]
@balavenkatesh3322 thanks for this submission but unfortunately we can't accept it as it brings less value to Topcoder members.
