### ISSUE TITLE
Flat Design Characteristics

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#35]
This is my article. May be useful

[Flat Design Characteristics (Wildan Abdul Azis).docx](https://github.com/topcoder-platform/thrive-submit/files/3931845/Flat.Design.Characteristics.Wildan.Abdul.Azis.docx)

**Comment by kkartunov** [comment]
passed PCheck

**Comment by Dara-K** [comment]
This article should be more elaborate with other indeptht knowledge about flat design. Also keep in mind to have minimum 500-600 words for it as it's very short now.

**Comment by KakaIdan** [comment]
This is my revised article. please check

[Flat Design Characteristic.docx](https://github.com/topcoder-platform/thrive-submit/files/3951763/Flat.Design.Characteristic.docx)

**Comment by Dara-K** [comment]
This looks better, but there is place for improvement.

- When writing an article pay attention to repeating words: for example I notice you have "flat design" in 2-3-4 consecutive sentences. That shouldn't be the case. Try to phrase things better.
- Let's add one image example for each characteristic of the flat design
- don't forget to add a cover image for all the articles you submit[ as per rules](https://github.com/topcoder-platform/thrive-submit/blob/master/README.md) - this will be used as the intro banner for the article (keep it relevant!) - the size should be minimum 760 pixels wide and 555 pixels tall.
- for the author, please write your Topcoder handle as well

**Comment by KakaIdan** [comment]
This is my revised article. please check

[Artikel kontes (Flat Design Characteristic).docx](https://github.com/topcoder-platform/thrive-submit/files/3954185/Artikel.kontes.Flat.Design.Characteristic.docx)

**Comment by Dara-K** [comment]
Thanks for the updates! We're almost there.

- Can you add a link from where you took the first image illustration? the one with the trees
- Let's add in the article an example of a mobile app flat design
- I think we can remove "Congratulations to design." from the end. It sounds weird.

**Comment by KakaIdan** [comment]
That's the design of my work 1 year ago. Because of the reason I don't need the link in the picture

**Comment by Dara-K** [comment]
In that case it would be nice to specify it and attach the source file. :)

**Comment by KakaIdan** [comment]
I don't have the original file (lost). because the design is old. finally I changed the photo using the source included ..

Please check the changes to my article ...
[Flat Design Characteristics (Wildan Abdul Azis).docx](https://github.com/topcoder-platform/thrive-submit/files/3969648/Flat.Design.Characteristics.Wildan.Abdul.Azis.docx)

**Comment by Dara-K** [comment]
This article is too short and barely talks about flat design. Please improve it considerably or let it go.

**Comment by KakaIdan** [comment]
This is my revisi
[Flat Design Characteristic.docx](https://github.com/topcoder-platform/thrive-submit/files/3973052/Flat.Design.Characteristic.docx)

**Comment by Dara-K** [comment]
This looks better but you still didn't do all the updates I mentioned:

- Let's add in the article an example of a mobile app flat design 
- Let's add all photos to be examples of Flat designs which highlight those points. It's fine if you take them from other sites like Dribbble as long as you give the credit
- I think we can remove "Congratulations to design." from the end. It sounds weird.
- Let's add more description for the 4 points, especially typography has just a little

**Comment by KakaIdan** [comment]
This is my revision

[Flat Design Characteristic.docx](https://github.com/topcoder-platform/thrive-submit/files/3989590/Flat.Design.Characteristic.docx)

**Comment by Dara-K** [comment]
Sorry, but this is still not detailed enough.

**Comment by KakaIdan** [comment]
Can you explain where my mistake is?

**Comment by Dara-K** [comment]
There are several aspects that are not well done here:
1. the photos are of flat design, but not related to web design or mobile
2. the flat design has more than 3 valuable characteristics
3. the description under each point it is relevant, but can have more strong points/ arguments made
4. the phrasing needs a lot of improvement
5. the style itself, of flat design, although still dominant, is already pretty old - 6 years
