### ISSUE TITLE
Photoshop functions and uses in graphic design

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#353]
Author			: Wildan Abdul Azis / Kaka_idan
Track Category	: Design
[Photoshop functions and uses in graphic design.docx](https://github.com/topcoder-platform/thrive-submit/files/5744364/Photoshop.functions.and.uses.in.graphic.design.docx)

**Comment by kkartunov** [comment]
@KakaIdan it fails the test with "Plagiarism was detected"
https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYBKcoAmUARgJYA2pMGANGAikgK4AOWYAyteXGHdPGToAEkwC2UAHbthUFAQC0MJApT4CAAngAPGH0jNJezACYAvjXADEqDNgAKUAM5PSANzgA1JKQi86DMxs2FxoPPrWQmiiEtIOzq4eGm4%2BfhpipE5MTv4GTEZYAMwWVrA26OwAsplOLHDkPAT6gazsHHUNpJIIEWVRMVJVNR2NGgDuqAROEYbGAIwlkH227ADqk11wLs2MrSHcuZG2A3Fg6-JoGjlGcJJ%2B0-yzWACsi0cVDuRQCKRymWI7ILsexfH5-JwA-jLETiQbYACqklQpB%2Bkig5A0ECQNwKj3yxleliWghW2HOBAAwgALVK5FrBMAAUUkVKkfjEtz0UJJMNia0mmJpvkOT0wrwAukA&page=plagiarism&breadcrumbs=true

**Comment by KakaIdan** [comment]
Im sorry. after I checked, I did not find plagiarism in this article

**Comment by Dara-K** [comment]
@KakaIdan This article is not really valuable. Photoshop is becoming pretty outdated for web and app design as the new tools are taking its place such as Figma, Sketch, XD. Talking about the basics of Photoshop is not helpful for the members. Sorry!
