### ISSUE TITLE
Understanding The Need for Dimensionality Reduction

### ISSUE THREAD

**Issue by goyalrohit** [topcoder-platform/thrive-submit#355]
Track Category: Data Science
Author: irohitgoyal (Rohit Goyal)
[Understanding_The_Need_for_Dimensionality_Reduction-RohitGoyal.docx](https://github.com/topcoder-platform/thrive-submit/files/5744501/Understanding_The_Need_for_Dimensionality_Reduction-RohitGoyal.docx)

**Comment by goyalrohit** [comment]
Data Science

**Comment by kkartunov** [comment]
passed min checks

**Comment by dimkadimon** [comment]
* "A difficult model" -> "A more complex model"
* "Visualization of data" you should explain that it is difficult to visualise more than 3 dimensions
* "The understanding of the data might not be correct" this does not make sense
* "Training is finding the best model parameters but with complex models, there are thousands of parameters value and hence the complexity arises. Also training such rapidly growing high dimensional complex models are time consuming time and training for too little time leads to bad modeling." Poor wording and hard to understand. Please revise
* Please remove the word "basically" - it looks unprofessional
* "It is to every time add a function to penalize" this doesn't make sense
* "we spit the data" -> "we split the data"
* "Cross-Validation:". Here you should describe k-fold cross-validation
* "Some example of these statistical techniques are Variance Thresholding, ANOVA, and Mutual Information" please provide references
* "Principal Component Analysis (PCA), Factor Analysis, Linear Discriminant Analysis (LDA), and Quadratic Discriminant Analysis (QDA)." please provide references
* "Feature Selection:" please explain how feature selection is performed. Provide references.
* " Multi-Dimensional Scaling (MDS), Isomap, Locally Linear Embedding (LLE), and Kernel Principal Component Analysis " provide references

**Comment by harshitmehta15** [comment]
@goyalrohit ^

**Comment by kkartunov** [comment]
closing due inactivity.
