### ISSUE TITLE
Voice AI/Automation and its Working

### ISSUE THREAD

**Issue by goyalrohit** [topcoder-platform/thrive-submit#357]
Track Category: Data Science
Author: irohitgoyal (Rohit Goyal)
[Voice AIAutomation and its Working-RohitGoyal.docx](https://github.com/topcoder-platform/thrive-submit/files/5744547/Voice.AIAutomation.and.its.Working-RohitGoyal.docx)

**Comment by kkartunov** [comment]
passed min checks

**Comment by dimkadimon** [comment]
* "voice command" -> "voice commands"
* "also are very likely to be abreast of the latest trends". I don't think this is true for the general reader
* "Our service offers scalability" whose service?!
* "NLU technology" please define NLU
* "It aids in the attainment of 100% accuracy in the performance of tasks". I don't think this is true. The technology still makes errors
* "designed through various complex programming commands" this is quite ambiguous
* "A continuous series of repetitive codes are programmed in software that directs the automation process to work in a certain algorithm." This is not true and not clear what is happening. Please provide literature and proper explanation how the technology works

**Comment by dimkadimon** [comment]
Please provide citations from literature. Please provide examples of what the technology can do, eg: convert speech to text, recognise people's voices etc. Please provide more details about how the technology works.

**Comment by harshitmehta15** [comment]
Hey @goyalrohit The article needs improvement as mentioned by the reviewer. Also I think this kind of theoritical article is available on the internet easily. If you are planning to improve and resubmit - please add some code and hands-on examples to have this article go on thrive.
