### ISSUE TITLE
Raster And Vector Differences In Graphic Design

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#358]
This is my article, please check
[Raster and vector differences in graphic design.zip](https://github.com/topcoder-platform/thrive-submit/files/5744650/Raster.and.vector.differences.in.graphic.design.zip)

**Comment by kkartunov** [comment]
passed min checks

**Comment by fajarmln** [comment]
@KakaIdan please provide the google docs version for review purpose

**Comment by KakaIdan** [comment]
I have fulfilled his request
https://docs.google.com/document/d/1I0Z8hE7i_taoFHWr9jN78Sphi9r8Sraa4wKLZpW7z7k/edit?usp=sharing

**Comment by fajarmln** [comment]
I am sorry, but the content looks really basic, The information about this article can be found a lot on the internet right now. We need some content that valuable in the present and still valid for the next few years. I will reject this article, thank you.
