### ISSUE TITLE
Flat Design Characteristic

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#359]
Author: Wildan Abdul Azis/Kaka_idan
Track Category: Design
[Flat Design Characteristic.docx](https://github.com/topcoder-platform/thrive-submit/files/5744691/Flat.Design.Characteristic.docx)

**Comment by kkartunov** [comment]
passed min checks

**Comment by fajarmln** [comment]
@KakaIdan please provide the google docs version for review purpose.

**Comment by KakaIdan** [comment]
I have fulfilled his request :)
https://docs.google.com/document/d/12HVRmNMpaXzv6jjLbFN6fuyn-28VBg47EcSNCFY1OL4/edit?usp=sharing

**Comment by fajarmln** [comment]
I am not able to open the google docs, so I check the word docs instead. 

The article content is a little bit dated, there's too many similar article about flat design in the web right now. 

Also, flat design is not longer the trending style right now, so I am going to reject this article, thank you.
