### ISSUE TITLE
What is the tensor in deep learning?

### ISSUE THREAD

**Issue by balavenkatesh3322** [topcoder-platform/thrive-submit#361]
Title: What is the tensor in deep learning?
Author: Bala Venkatesh
Track Category: Data Science
Subcategory: Theory
Tag: Python, Deep learning, Machine learning

User name :- balavenkatesh.s
mailid :- venkateshpnk22@gmail.com

[Blog link](https://docs.google.com/document/d/1GHG8D2aZK9wHHAyke29agg5tiY04Ck0Oo6LVedgvaCA/edit?usp=sharing)

**Comment by kkartunov** [comment]
passed min checks

**Comment by harshitmehta15** [comment]
Hi @balavenkatesh3322 Several easily accessible articles are available on the internet around Tensors. The reviewer had a similar point of view.

I suggest we should look at some interesting topic on which not much is available or written or something that 

I will have to, unfortunately, reject this. 

Really liked your first articles. Looking forward to more of your submissions. Feel free to confirm the topic and bullet points before writing :)
