### ISSUE TITLE
Various kinds of graphic media

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#362]
Author: Wildan Abdul Azis / Kaka_idan
Track Category: Design
[Various kinds of graphic media.docx](https://github.com/topcoder-platform/thrive-submit/files/5746097/Various.kinds.of.graphic.media.docx)

**Comment by kkartunov** [comment]
@KakaIdan it fails the test with "Significant plagiarism was detected". Please update it.
https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYDCSC2ADgAoCuAdhDGADRgIpKmFZhmUymwCWS5tkWIlRoAEqXxR%2B2dlS4xe5AATdlEAoSbkAJgHp1RADZwAHkoDOccvEpxzA9RWqYAjAF8a4aPGTpWxKHNzbgA3OAA1JG4IOAEGJhZsAGUYNGMHIV8xCSl-QOCwpRComKV8bnNSSwctZxcAJg8vTJFWAFkK80I4Q2NtOMZmViTu3tUEDJ8RcUlpMA6g0b6lAHdUbXs6R2ssd09BKb9sAHV11TtN%2BkHEsBS02K2W9Bnck-W0CysbGMvt5wA2JoHYRHNiGKAIbhQFAVfADBL%2BcGQ6GwyYg7KzVgAVXIqG4kPIUEMSnU1i%2BNScu0a%2B286NYpxQ2hwAAsSg8rgjsABRcjMqQxfDkx6HDGvMAM7Qk1nRdl-XYABiBtKy-kYuIol3iQ2wAHEUFB8JIUGisi85sQ1VolFVZbVdm4ALpAA&page=plagiarism&breadcrumbs=true

**Comment by KakaIdan** [comment]
My revision
[Various kinds of graphic media (Revision 1).docx](https://github.com/topcoder-platform/thrive-submit/files/5747587/Various.kinds.of.graphic.media.Revision.1.docx)

**Comment by Dara-K** [comment]
@KakaIdan  I have reviewed this article and is too basic and simple for the quality of articles we have on Thrive. Next times, please focus on providing content that is interesting to the members and which add more value.

Thank you!
