### ISSUE TITLE
Learn to Use Figma; Practice Design Two Screen of Mobile Application

### ISSUE THREAD

**Issue by kreasindo513** [topcoder-platform/thrive-submit#368]
Please review in docx file and google docs link as well, Thank you
[Learn to Use Figma to Design Mobile Application.docx](https://github.com/topcoder-platform/thrive-submit/files/5753448/Learn.to.Use.Figma.to.Design.Mobile.Application.docx)
[https://docs.google.com/document/d/1eWS-41xekDJJyXRP0mO0XkdDCa2LvlzYk30ARxp-zMw/edit?usp=sharing](url)

**Comment by kkartunov** [comment]
passed min checks

**Comment by fajarmln** [comment]
@kreasindo513 

This article is too basic and still incomplete (no screenshot of the steps and further explanation in each step), it depends too much with 3rd party plugin and GUI kit from other resources too. I will reject this article.

**Comment by kreasindo513** [comment]
Hi Bang @fajarmln 
Thanks for your review and feedback, I will update the article with design tips/tricks which valuable to Topcoder designer. I saw the Figma quit the popular platform, but I can not see any article about Figma in Thrive.

**Comment by fajarmln** [comment]
Figma just recently being accepted as a new tool in the Topcoder Design challenge, so we don't have a tutorial for this tool yet. If you want to create a Figma tutorial (but with good details), we will be happy to see it.
