### ISSUE TITLE
How to make a pattern design using adobe photoshop

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#374]
This is my article "how to make a pattern design"
[How to make a pattern design using adobe photoshop.zip](https://github.com/topcoder-platform/thrive-submit/files/5757695/How.to.make.a.pattern.design.using.adobe.photoshop.zip)

**Comment by kkartunov** [comment]
passed min checks

**Comment by fajarmln** [comment]
@KakaIdan This tutorial is really basic and tons of similar article already available in the internet, one of them available in the adobe help forum since 2017 which contains lesser steps: https://helpx.adobe.com/photoshop/using/creating-patterns.html

I will reject this tutorial, thank you.
