### ISSUE TITLE
An Overview of Blockchain Technology

### ISSUE THREAD

**Issue by goyalrohit** [topcoder-platform/thrive-submit#376]
Track Category: Design

Author: irohitgoyal (Rohit Goyal)

[An Overview of Blockchain Technology-RohitGoyal.docx](https://github.com/topcoder-platform/thrive-submit/files/5764423/An.Overview.of.Blockchain.Technology-RohitGoyal.docx)

**Comment by kkartunov** [comment]
@goyalrohit thanks for this submission but we already have [articles covering](https://www.topcoder.com/thrive/search?phrase=Blockchain) the basics of Blockchain. If you want to write on the topic please go more deeper and detailed.
