### ISSUE TITLE
Understanding the Different Types of Artificial Intelligence

### ISSUE THREAD

**Issue by goyalrohit** [topcoder-platform/thrive-submit#377]
Track Category: Data Science
Author: irohitgoyal (Rohit Goyal)

[Understanding the Different Types of Artificial Intelligence-RohitGoyal.docx](https://github.com/topcoder-platform/thrive-submit/files/5768605/Understanding.the.Different.Types.of.Artificial.Intelligence-RohitGoyal.docx)

**Comment by kkartunov** [comment]
passed min checks

@goyalrohit fyi, this artcile will be awarded $50 if it passes review.

**Comment by harshitmehta15** [comment]
@goyalrohit can you work on enhancing this article. Detailing each type and even adding an examples. There are several articles available on the internet and if you can think of something that would set it apart. - we can publish this. :)

**Comment by kkartunov** [comment]
closing due inactivity.
