### ISSUE TITLE
An Overview of Robotic Process Automation

### ISSUE THREAD

**Issue by goyalrohit** [topcoder-platform/thrive-submit#378]
Track Category: Data Science
Author: irohitgoyal (Rohit Goyal)

[An Overview of Robotic Process Automation.docx](https://github.com/topcoder-platform/thrive-submit/files/5770004/An.Overview.of.Robotic.Process.Automation.docx)

**Comment by kkartunov** [comment]
passed min checks

**Comment by harshitmehta15** [comment]
Hey @goyalrohit ,
Unfortunately, I will have to reject this one. There are several articles available around this. 

If you'd like to write about RPA - I suggest adding examples to the Topcoder product or any famous Business us. Explaining it with an example and linking variour relevant resources and even some learning paths or projects a member can take is something that would make the article stand out.
