### ISSUE TITLE
SQL Database Performance Tuning

### ISSUE THREAD

**Issue by ga20091049** [topcoder-platform/thrive-submit#38]
[sql_database_tuning_tips.docx](https://github.com/topcoder-platform/thrive-submit/files/3932299/sql_database_tuning_tips.docx)

Please review the Article posted

**Comment by kkartunov** [comment]
passed PCheck

**Comment by billsedison** [comment]
@ga20091049 

Looks most of your bullet points are from this book: https://books.google.com.hk/books?id=sX9hFLWLYCQC&pg=PA22&lpg=PA22&dq=+Give+prominence+stage+1+over+stage+2+predicates&source=bl&ots=VtrqS4B6j-&sig=ACfU3U1P4-Hy9YOrc_swxkg95Cvu9ybhPg&hl=en&sa=X&ved=2ahUKEwjkjLDi3qjmAhUbPXAKHauGADEQ6AEwAHoECAcQAg#v=onepage&q=Give%20prominence%20stage%201%20over%20stage%202%20predicates&f=false

And it's related to DB2 SQL, not the universal SQL.

Sorry, I can't accept this article.
