### ISSUE TITLE
Downloading Data From AWS S3

### ISSUE THREAD

**Issue by ksmacleod99** [topcoder-platform/thrive-submit#380]
https://docs.google.com/document/d/1MoQiRyoqVP62GoOEQs-DdI0woHtFf0Spi8TP-7KUCgY/edit?usp=sharing

**Comment by kkartunov** [comment]
Hey, @ksmacleod99 article fails passing plagiarism check. Please correct, update it, and resubmit.

https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYBCUDOAlhAAoCuAdhDGADRgIpJkAOWY5VMZshSFdSLESo0ACTIBbKAOwBhJJOkACSYXxl8cZQHdCMABaEKyiABsomuPkERmFGpgCMAX1rho8ZOnYLJLTmpBRmY2bEDuXn5bYW9xKRl2CJ4YPhNjU0UWewATAHo7fzM4AA9lLQc4Kmtbe0dXdyEvUXYAETh4FDUKOBQbehDWdgBxFCglKBQY5vQJaVkwds7u3uUrZQAKKDyZPMM4PaN8WmUOiAA6AEpaykcAJjcPWJbwgiIANzgANSRiOGCmENsABlGBoYrTESzBILEhvQifZTvX4QbRqDRaG4OLAANkeTShGGwAFl1PgWHAzMUcgDQuxgRSqcYEJC4nNEiSyYzqbpUDl%2BpA6lgAMz4zyE9gAdT5xmsAsGYTAoPB-3o4rZMKlfLQ5Sq8GqArstywD0a6peYAUVKQAEcyIQoGZaUClWCIWrntD5uwAJIUKAsFhMIMO%2BCZa12h1mdSSQ1C5xiz1EjgWBAOlAx52Kkip9OZj0zeLe7AAVQoqEIaf9ZkylWxavjABZE4X2AAxVDSGCpCgsgaAxXK90EjXFsA%2B-zB1YAM07sB7fcFxoTZqTWpQOTkBhRqoYA-YAFEKAYZKjJHrWaJ2QtpRvTNu-ljHM3V635BYM2Cs-S3bvzV6OXHBwM3FZR4BKGgG2XVwAF0gA&page=plagiarism&breadcrumbs=true

**Comment by ksmacleod99** [comment]
I'm not trying to be difficult, but the Grammarly check is not useful in pointing out where the plagiarism is. 

We do quote (and cite) the AWS documentation for parts of this article. Could Grammarly be picking up on that?

**Comment by kkartunov** [comment]
@ksmacleod99 we have a repo rule to consider only articles that pass the Grammarly check. Please, make it pass by tweaking the sections you mention. I hope it helps...

**Comment by harshitmehta15** [comment]
Hey @kkartunov - Kelly is an admin and we are publishing this as a help article. This would be Topcoder General Category :)

**Comment by kkartunov** [comment]
Published https://www.topcoder.com/thrive/articles/downloading-data-from-aws-s3
Thank you @ksmacleod99 and @harshitmehta15
