### ISSUE TITLE
Demonstrate process of Data science clustering algorithm

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#39]
[Demonstrate process of Data science clustering algorithm.docx](https://github.com/topcoder-platform/thrive-submit/files/3932953/Demonstrate.process.of.Data.science.clustering.algorithm.docx)

**Comment by kkartunov** [comment]
passed PCheck

**Comment by harshitmehta123** [comment]
I think the title should be Basics of Clustering Algorithms or something more for the newbies.

Also, can you make and add descriptive images for the Hierarchical Clustering?

@t0070926

**Comment by t0070926** [comment]
[Data Science-Basics of Clustering Algorithms.docx](https://github.com/topcoder-platform/thrive-submit/files/3963253/Data.Science-Basics.of.Clustering.Algorithms.docx)

**Comment by t0070926** [comment]
Changed title and added  required images as you suggested
