### ISSUE TITLE
Pros and Cons between Different Bloc State Management Approaches

### ISSUE THREAD

**Issue by RStackCode** [topcoder-platform/thrive-submit#390]
a

**Comment by kkartunov** [comment]
@RStackCode thanks for your submission. Please check bellow and update your article:
- convert code blocks to text so we can copy them
- fails the [plagiarism test](https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYBCUDOAlhAAoCuAdhDGADRgIpJkAOWY5VMZshSFdSLESo0ACTIBbKAOwBhJJOkACSYXxl8cZQHdCMABaEKyiABsomuPkERmFGpgCMAX1rho8ZOnYLJLTmpBRmY2bEDuXn5bYW9xKRl2CJ4YPhNjU0UWewATAHo7fzM4AA9lLQc4Kmtbe0cAVjcPWNF2ABE4eBQ1CjgUG3oQ1nYAcRQoJSgUGK9RCWlZMA6unr7lK2UACig8mTzDOH2jfFplTogAOgBKWspHABYmoVmfbABVCgBrCiQdAUGmMNsABlFhwMxmYwIGYidDzRLvL4-P66VA5AaQOpYABMT08sIw2AAsup8GCIXAcsFAWEwKDwZCKND6Pi4vDFiT8GSGZTUSh0bcHFhHu5ngT2AB1NHGawYoa04EwNDFGFshKLKX8tDlKrwaoYux3HF4lqvDgWBCEKbqSTU0JJC1WlA21VzdXsD6oQiWihQMyZSpCllYzCNUWs1rhFBwbJEVL8OU00bjSbTFmm%2BILSVMJnKVCqUlQ5QsaOx-RpA0h1zhjO%2BJAQpAARzIVrMdqBdKVKvTL0zCLAAElfSwS0gS1b4JkG83WzbK0bMLia73JWi5AYkMQ4O3aQBRCgGGQQOCSXWuuHu7CanKmDdbwUNE0r%2BQWZ1KnfsRXK7c9gns9hDjAzr4so8AlDQwYLq4AC6QA&page=plagiarism&breadcrumbs=true) - correct and make it pass

**Comment by RStackCode** [comment]
Thanks, I've converted the images into code blocks of text. For the plagiarism test, grammarly doesn't allow me to view it without a premium account. I've also typed everything one by one in my article and didn't even look at other sources while doing so. I do think that the plagiarism flag is a false positive.

**Comment by kkartunov** [comment]
Thanks @RStackCode. I re-tested the article with another tool and it looks fine - no plagiarism.
Let's move this one to review...

**Comment by kkartunov** [comment]
Hey, @RStackCode, great article. Can you please add setcion on how to setup env and run the code provided? Will be helpful for the newbie members. Thanks

**Comment by RStackCode** [comment]
Thanks @kkartunov , the flutter team has a really good [documentation](https://flutter.dev/docs/get-started/install) on how to install and set flutter up. Would this be enough?

**Comment by kkartunov** [comment]
Yeah, let's add section to referr to it with few sentances. Thanks

**Comment by CoderUni** [comment]
@kkartunov When will the article be published?

**Comment by kkartunov** [comment]
@CoderUni have you added the section as requested above?

**Comment by CoderUni** [comment]
I've added it now

**Comment by kkartunov** [comment]
closing due inactivity.
