### ISSUE TITLE
Order Bys & Group Bys

### ISSUE THREAD

**Issue by JoshuaSmart-Olufemi** [topcoder-platform/thrive-submit#392]
Track Category: Data Science

Author: JoshuaSmart

Article Link: https://drive.google.com/file/d/1A6tsuAHpwF17dXxjYfdZmKMtST1Z_3fR/view?usp=sharing

**Comment by kkartunov** [comment]
Hi @JoshuaSmart-Olufemi, thanks for submission.
Please update article to pass plagiarism tests and resubmit.
https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYBCUDOAlhAAoCuAdhDGADRgIpJkAOWY5VMZshSFdSLESo0ACTIBbKAOwBhJJOkACSYXxl8cZQHdCMABaEKyiABsomuPkERmFGpgCMAX1rho8ZOnYLJLTmpBRmY2bEDuXn5bYW9xKRl2CJ4YPhNjU0UWewATAHo7fzM4AA9lLQc4Kmtbe0cAFjcPWNF2AFUKAGsKJB0BehDWdgBlFjgzM2MEGK9RCWlZMA7u3pMdVBybejtKR1d3IVmfbAAlOCgcqAAjQkmYDAGmIexh%2B%2BKZkXR5xOwxKBQcgBaGBIQEoc45ZTwEo0bZ1LD7ZpHDDhAhEABucAAakhiHBgk8wmBXmh3tsWl8EosSGjCJjlOjcRBtGoNFparsEYjDp8UWAALLqfBjCZwHIE0IjEWTCjTcnI76LQX4YXjYqQ9YAraQeGYABMTR5cXYAHUNsZrNrBkSSWSjXMqaaNmhylV4NVtTsHAjDZ5eUkLAhCP91JIJc8OIHgyhQx84or2j0Y0GKFAzJlKt64ZzMI0Dn7jS8xhBg2Y5AZ-lBqHAUFbCUlKNQUmk4w6FuxlVZlEgAGautR2Mz8fC0ZQARzISBgURM0hQnRHyjgMAgADoOd7nL6KXyzQDy0z8Y9JdgAKIUCvVSRu1uU9vYPeQiAGQ8bxwANm3yN8Fhj93DNpvEe9p3j8YAAJIODGfpQqUsI6jmjQALpAA&page=plagiarism&breadcrumbs=true

**Comment by JoshuaSmart-Olufemi** [comment]
Hello Kiril. Thanks for the feedback. I'm having a bit of trouble with the
plagiarism checker. The article I wrote was very organic and
straightforward. I didn't even consult any articles before writing it. My
guess is that, because this is a common topic with a lot of entries on
Google, my content is being flagged as plagiarized. If you don't mind, I
have attached a Word document of this article so you can have a look. Even
the examples in my article are examples I came up with myself. So I don't
understand why Grammarly is flagging it as plagiarized.

**Comment by kkartunov** [comment]
@JoshuaSmart-Olufemi I rechecked article with another tool. Attached the report.
We can move this to review.
[plagiarismdetector (5).pdf](https://github.com/topcoder-platform/thrive-submit/files/6655321/plagiarismdetector.5.pdf)

**Comment by JoshuaSmart-Olufemi** [comment]
Thank you for the feedback. In the meantime, I submitted a second article
on a different topic. Can that be counted as my official second article for
TopCoder, if and when it is reviewed and approved?

**Comment by kkartunov** [comment]
@JoshuaSmart-Olufemi according our rules articles will be caounted/payed after they are published.
You welcome to submit meantime, until you waut for review feedback.
Thanks much for your submissions!

**Comment by JoshuaSmart-Olufemi** [comment]
Hi again. I submitted an article titled "Order Bys & Group Bys" to the platform about a week ago but haven't got any feedback yet from TopCoder on the status of the article.

**Comment by kkartunov** [comment]
Hey @JoshuaSmart-Olufemi sorry for delay on this. We will accept the article for Development track. 
Please add a table at the end that summarizes the difference between Order by and group by clause. Something like:
| #   |      GROUP BY      |  ORDER BY |
|----------|:-------------:|------:|
| 1 |  Lorem ipsum... | Lorem ipsum... |

**Comment by JoshuaSmart-Olufemi** [comment]
Do I have to re-submit the edited version with the table and take it
through the plagiarism detector or can I submit it here, on this email
correspondence?

**Comment by JoshuaSmart-Olufemi** [comment]
I have updated the article as requested. Here's the link: https://drive.google.com/file/d/1A6tsuAHpwF17dXxjYfdZmKMtST1Z_3fR/view?usp=sharing

**Comment by JoshuaSmart-Olufemi** [comment]
I have updated the article as requested and posted the link to the updated
article on the GitHub correspondence
