### ISSUE TITLE
Create A Full Stack To-Do Application Using React Native and Strapi 

### ISSUE THREAD

**Issue by facelessdevhack** [topcoder-platform/thrive-submit#397]

**Comment by kkartunov** [comment]
Hi @facelessdevhack this submission has insufficient content. Please see to meet minimum requirements as described in our guide  https://www.topcoder.com/thrive/articles/Submitting%20a%20Thrive%20Article. Also note that provided link is for DigitalOcean.

**Comment by kkartunov** [comment]
closing due inactivity.
