### ISSUE TITLE
Problem solving approach (with Javascript)

### ISSUE THREAD

**Issue by hirwablessing** [topcoder-platform/thrive-submit#399]
**Track:** Software Engineering | Javascript Programming
**Author:** [Blessing Hirwa](https://www.topcoder.com/members/blessinghirwa)

**Article:** https://docs.google.com/document/d/1JkgUXu6eynT_ax59RC5OYiOxFlMSb8vdl0irkbPPhhk/edit?usp=sharing

**Comment by hirwablessing** [comment]
Please check out my new article and let me know if there's a problem.

cc: @kkartunov

**Comment by kkartunov** [comment]
@hirwablessing please move to the new repo, check the readme for instructions. We no longer accepting articles here.

**Comment by hirwablessing** [comment]
Please check out my new article and let me know if there's a problem.

cc: @kkartunov

**Comment by hirwablessing** [comment]
Moving now...
