### ISSUE TITLE
The future of quantum computing

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#4]
Hello, Kindly find the files in the zip-file below:
[thrive.zip](https://github.com/topcoder-platform/thrive-submit/files/3917614/thrive.zip)

**Comment by kkartunov** [comment]
Passed plagiarism check

**Comment by Rokit12** [comment]
thanks

**Comment by billsedison** [comment]
@Rokit12 This is just a high-level introduction of quantum computing, it is good but not that related to our Development track. We can easily get a similar introduction by Googling "quantum computers vs classical computers". For example: https://www.geeksforgeeks.org/conventional-computing-vs-quantum-computing/

What we are looking for is the original content with more concrete details, like special tools or tips, specific technology, theories etc.

**Comment by Rokit12** [comment]
cool
