### ISSUE TITLE
Get To Know The Golden Ratio In Graphic Design

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#41]
please review my article

[Get To Know The Golden Ratio In Graphic Design (Wildan Abdul Azis).docx](https://github.com/topcoder-platform/thrive-submit/files/3933348/Get.To.Know.The.Golden.Ratio.In.Graphic.Design.Wildan.Abdul.Azis.docx)

**Comment by kkartunov** [comment]
@KakaIdan Significant plagiarism was detected. Please, correct.

**Comment by KakaIdan** [comment]
Can be explained, where the error lies ?

**Comment by kkartunov** [comment]
@KakaIdan make it pass check here https://www.grammarly.com/plagiarism-checker otherwise we can't accept it for review.

**Comment by kkartunov** [comment]
@KakaIdan are you working on this one?
