### ISSUE TITLE
Performance problem in an IMS environment

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#44]
[Performance problem in an IMS environment.docx](https://github.com/topcoder-platform/thrive-submit/files/3934760/Performance.problem.in.an.IMS.environment.docx)

**Comment by kkartunov** [comment]
passed PCeck

**Comment by billsedison** [comment]
![image](https://user-images.githubusercontent.com/5657467/70443087-782eaa80-1ad2-11ea-8787-42d842f0ec2e.png)

The format of your document is bad, and sentences of your document are not fluent. I'm not sure if you are just randomly picking some sentences from a book. If so, please STOP doing this. Thanks.
