### ISSUE TITLE
Oracle Working with Materialized Query Tables

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#45]
[Oracle Working with Materialized Query Tables.docx](https://github.com/topcoder-platform/thrive-submit/files/3935391/Oracle.Working.with.Materialized.Query.Tables.docx)

**Comment by kkartunov** [comment]
passed PCheck

**Comment by billsedison** [comment]
@t0070926 

It's from https://docs.oracle.com/cd/E66686_01/pt855pbr1/eng/pt/tadm/task_WorkingWithMaterializedQueryTables.html
