### ISSUE TITLE
Integrate CICS (Customer Information Control System) online with JAVA

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#47]
[Integrate_CICS_JAVA.docx](https://github.com/topcoder-platform/thrive-submit/files/3935860/Integrate_CICS_JAVA.docx)

**Comment by kkartunov** [comment]
passed PCheck

**Comment by billsedison** [comment]
It's from https://www.ibm.com/support/knowledgecenter/en/SSGMCP_5.3.0/com.ibm.cics.ts.java.doc/topics/gettingstarted_jcicsproject.html

https://www.ibm.com/support/knowledgecenter/en/SSGMCP_4.2.0/com.ibm.cics.ts.java.doc/topics/gettingstarted_sdk.html

....
