### ISSUE TITLE
Integrate Hadoop eco system with My sql database

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#48]
[Integrate_Hadoop_My_sqldatabase.docx](https://github.com/topcoder-platform/thrive-submit/files/3935966/Integrate_Hadoop_My_sqldatabase.docx)

**Comment by kkartunov** [comment]
passed PCheck.

**Comment by billsedison** [comment]
@t0070926 

The format is pretty bad and the sentences almost cannot read.
