### ISSUE TITLE
HOW A IMS database can become corrupted and Recovery process

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#49]
[HOW A IMS database can become corrupted and Recovery process.docx](https://github.com/topcoder-platform/thrive-submit/files/3936308/HOW.A.IMS.database.can.become.corrupted.and.Recovery.process.docx)

**Comment by kkartunov** [comment]
passed PCheck

**Comment by billsedison** [comment]
It's from https://www.ibm.com/support/knowledgecenter/en/SSCLV2_2.1.0/com.ibm.imstools.hppc.doc.ug/topics/fabpu_dbrp-howcorrupted.htm
