### ISSUE TITLE
LOB(Large Objects) implementation in db2 and Oracle

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#50]
[LOB(Large Objects) implementation in db2 and Oracle.docx](https://github.com/topcoder-platform/thrive-submit/files/3937454/LOB.Large.Objects.implementation.in.db2.and.Oracle.docx)

**Comment by kkartunov** [comment]
@t0070926 Plagiarism was detected. Please fix and notify when ready.

**Comment by t0070926** [comment]
[Large_Objects_db2_Oracle.docx](https://github.com/topcoder-platform/thrive-submit/files/3938703/Large_Objects_db2_Oracle.docx)

**Comment by t0070926** [comment]
Completed Plagiarism check please look and process

**Comment by billsedison** [comment]
The sentences are randomly picked from this book https://books.google.com.hk/books?id=zrYFCIAFXw8C&pg=PA171&lpg=PA171&dq=%22a+table+contains+a+LOB+column%22&source=bl&ots=hpCoV2BOLb&sig=ACfU3U0ZLtRkDAoZF48XCPg88TH_TjIPvg&hl=en&sa=X&ved=2ahUKEwjxrrCr5ajmAhWRbN4KHVEWBksQ6AEwA3oECAkQAg#v=onepage&q=%22a%20table%20contains%20a%20LOB%20column%22&f=false

The entire sentences are not fluent and almost cannot read.
