### ISSUE TITLE
Connection from LUW ( Linux Unix Windows ) to Mainframe DB2

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#51]
[Connection from LUW ( Linux Unix Windows ) to Mainframe DB2.docx](https://github.com/topcoder-platform/thrive-submit/files/3937806/Connection.from.LUW.Linux.Unix.Windows.to.Mainframe.DB2.docx)

**Comment by kkartunov** [comment]
passed PCheck

**Comment by billsedison** [comment]
@t0070926 The document format is pretty bad, missing some screenshots too. And looks the entire content was from some tutorial. The article is not helpful.
