### ISSUE TITLE
The Best Way to Turn Ideas Into Sketch Designs

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#52]
Track Category: Design

[Hasanozie - The Best Way to Turn Ideas Into Sketch Designs.docx](https://github.com/topcoder-platform/thrive-submit/files/3938196/Hasanozie.-.The.Best.Way.to.Turn.Ideas.Into.Sketch.Designs.docx)

**Comment by kkartunov** [comment]
passed PCheck

**Comment by Dara-K** [comment]
We already have a similar article: https://www.topcoder.com/why-you-should-sketch-before-design/ . Please check for existing articles on same theme/ topic on the blog.

**Comment by hasanozie** [comment]
Hi @Dara-K ,
Thank you for reviewing this article.
Sorry because I didn't check the existing articles carefully. Next, I will make sure the article that I will make is not yet available on thrive
