### ISSUE TITLE
DB2LUW- Table partitioning and multidimensional clustering tables

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#53]
[DB2LUW- Table partitioning and multidimensional clustering tables.docx](https://github.com/topcoder-platform/thrive-submit/files/3939182/DB2LUW-.Table.partitioning.and.multidimensional.clustering.tables.docx)

**Comment by kkartunov** [comment]
passed PCheck.

**Comment by billsedison** [comment]
It's from https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.5.0/com.ibm.db2.luw.admin.partition.doc/doc/c0021605.html

Please STOP copying from the official help document and try to CHEAT the Grammarly plagiarism checker.
