### ISSUE TITLE
Why Design Principles Are Very Important For Graphic Designers

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#55]
Track Category: Design

[Hasanozie - Why Design Principles Are Very Important For Graphic Designers.docx](https://github.com/topcoder-platform/thrive-submit/files/3940806/Hasanozie.-.Why.Design.Principles.Are.Very.Important.For.Graphic.Designers.docx)

**Comment by kkartunov** [comment]
passed PCheck.

**Comment by Dara-K** [comment]
Sorry, but we already have a similar article: https://www.topcoder.com/10-useful-design-techniques-master-visual-hierarchy/

**Comment by hasanozie** [comment]
Hi @Dara-K  ,
Thank you for reviewing this article.
Sorry because I didn't check the existing articles carefully. Next, I will make sure the article that I will make is not yet available on thrive
