### ISSUE TITLE
How to Export Adobe XD Files to Adobe Photoshop

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#58]
Track Category: Design

[Hasanozie - How to Export Adobe XD Files to Adobe Photoshop.docx](https://github.com/topcoder-platform/thrive-submit/files/3943036/Hasanozie.-.How.to.Export.Adobe.XD.Files.to.Adobe.Photoshop.docx)

**Comment by kkartunov** [comment]
passed PCheck

**Comment by Dara-K** [comment]
I don't think this is of interest to our members since most of the design challenges accept XD format now as it's easier to share the prototype specifications with the coder, compared to Photoshop where we can't do that easily.

**Comment by hasanozie** [comment]
Hi @Dara-K ,
Thank you for reviewing this article.
I will try to make a better article
