### ISSUE TITLE
Integrate Db2 Luw and Db2 Mainframe

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#62]
[Integrate Db2 Luw and Db2 Mainframe.docx](https://github.com/topcoder-platform/thrive-submit/files/3945142/Integrate.Db2.Luw.and.Db2.Mainframe.docx)

**Comment by kkartunov** [comment]
@t0070926 Need to be > 500 words length.

**Comment by t0070926** [comment]
[Uploading Integrate Db2 Luw and Db2 Mainframe.docx…]

**Comment by t0070926** [comment]
[Integrate Db2 Luw and Db2 Mainframe.docx](https://github.com/topcoder-platform/thrive-submit/files/3955939/Integrate.Db2.Luw.and.Db2.Mainframe.docx)

**Comment by kkartunov** [comment]
passed PCheck and min len check

**Comment by billsedison** [comment]
The content is the same as the closed one. PLEASE DON'T JUST CREATE A NEW NAME FOR THE SAME CONTENT!!!

https://github.com/topcoder-platform/thrive-submit/issues/51
