### ISSUE TITLE
Pointer Issue in IMS DB and Fix

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#63]
[Pointer Issue in IMS DB and Fix.docx](https://github.com/topcoder-platform/thrive-submit/files/3945582/Pointer.Issue.in.IMS.DB.and.Fix.docx)

**Comment by kkartunov** [comment]
passed PCheck and length check.

**Comment by billsedison** [comment]
The format is pretty bad and the sentences are not fluent.
