### ISSUE TITLE
React JS to include data in suspense: Declaring data to be rendered through API

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#66]
Kindly find the below document
[Thrive4.zip](https://github.com/topcoder-platform/thrive-submit/files/3950581/Thrive4.zip)

**Comment by kkartunov** [comment]
passed Pcheck and min length check

**Comment by Rokit12** [comment]
ooh hope this one passes

**Comment by billsedison** [comment]
@Rokit12 The format is pretty bad. You need to improve the format of your articie.

For example
1. Use a different font for the code
2. Fix the case issue in the code, please note the Javascript is case sensitive.

So the following code case is incorrect and will cause syntax error.
![image](https://user-images.githubusercontent.com/5657467/70880202-1ce54680-2003-11ea-8cfe-a29c8d167426.png)

**Comment by Rokit12** [comment]
Hello, kindly the corrected article below:
[TITLE_ React JS to include data in suspense_ Declaring data to be rendered through API (1).docx](https://github.com/topcoder-platform/thrive-submit/files/3966278/TITLE_.React.JS.to.include.data.in.suspense_.Declaring.data.to.be.rendered.through.API.1.docx)

**Comment by billsedison** [comment]
@Rokit12 Double check and I found the code snippet the same as here

```
const wrapPromise = (promise) => {
    let status = 'pending'; 
    let result = '';
    let suspender = promise.then(r => {
        status = 'success'; 
        result = r;
    }, e => { 
        status = 'error'; 
        result = e; 
    }) 

    return {
        read(){
            if (status === 'pending'){
                throw suspender; 
            } else if (status === 'error'){
                throw result; 
            }
            return result; 
        }
    }
} 

export const createResource = () => {
    return {
        person1: wrapPromise(fetchPerson()),
        person2: wrapPromise(fetchPerson()),
        person3: wrapPromise(fetchPerson()),
        person4: wrapPromise(fetchPerson()),
        person5: wrapPromise(fetchPerson()),
        person6: wrapPromise(fetchPerson())
    }
}
```

https://stackoverflow.com/questions/58617799/react-suspense-concurrent-suspenselist-order-not-working

**Comment by Rokit12** [comment]
Though i never checked there. i wrote myself. I dont understand

**Comment by Rokit12** [comment]
Hello, i HAVE REMOVED THE PART
[TITLE_ React JS to include data in suspense_ Declaring data to be rendered through API (2).docx](https://github.com/topcoder-platform/thrive-submit/files/3979075/TITLE_.React.JS.to.include.data.in.suspense_.Declaring.data.to.be.rendered.through.API.2.docx)
 CHECK BELOW PLEASE
