### ISSUE TITLE
LOB (Large Objects) implementation and Reorg in db2 

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#69]
[Large_Objects_db2.docx](https://github.com/topcoder-platform/thrive-submit/files/3953863/Large_Objects_db2.docx)

**Comment by kkartunov** [comment]
@t0070926 how is this different from https://github.com/topcoder-platform/thrive-submit/issues/60 this one?

**Please, STOP closing and reopening issues for the same articles. This is your second warning of doing against repo rules. If it occurs again I will be forced to remove you from repo and challenge!**

**Comment by t0070926** [comment]
as  article is less than 500 words i closed ok going forward i will take care

**Comment by kkartunov** [comment]
passed PCheck and min length check

**Comment by billsedison** [comment]
@t0070926 The sentences are not fluent and the format is bad.

I can't see any LOB (Large Objects) implementation in db2.

And the link of the banner image is broken: https://lh3.googleusercontent.com/zchtlS9Y4g0lhO2IZo0ZW34031dAGcttRHIaLPOMyXmu3951kHRTsabDfUVVwRU4BaWyDQ=s85
