### ISSUE TITLE
How to Become a Professional Graphic Designer

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#7]
Hi, Please review my article
Thanks :)

[Thrive - Hasanozie - How To Become A Professional Graphic Designer Without Being Graduate In Design.zip](https://github.com/topcoder-platform/thrive-submit/files/3920262/Thrive.-.Hasanozie.-.How.To.Become.A.Professional.Graphic.Designer.Without.Being.Graduate.In.Design.zip)

**Comment by kkartunov** [comment]
Passed Plagiarism check

**Comment by Dara-K** [comment]
Hi! The main points in becoming a professional graphic designer is to learn the basics: typography, color theory, hierarchy, etc. learn the tools, create a portfolio and find the right mentor/ community to show off your design and improve faster. Taste can be educated and business writing to present your ideas come later when you have to sell your work to customers.

Many of these points can already be found here (same theme article) https://www.topcoder.com/how-to-start-a-career-as-a-ui-ux-designer/

**Comment by hasanozie** [comment]
Hi @Dara-K ,
Thank you for reviewing this article.
I will try to make a better article :)
