### ISSUE TITLE
My Journey with TopCoder Community

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/thrive-submit#70]
[My Journey with TopCoder Community.docx](https://github.com/topcoder-platform/thrive-submit/files/3954169/My.Journey.with.TopCoder.Community.docx)

Track Category: QA

**Comment by kkartunov** [comment]
@CreeyaSean article has to be > 500 words length and pass Plagiarism Check https://www.grammarly.com/plagiarism-checker

**Comment by CreeyaSean** [comment]
[My Journey with TopCoder Community.docx](https://github.com/topcoder-platform/thrive-submit/files/3954654/My.Journey.with.TopCoder.Community.docx)


Updated.

**Comment by CreeyaSean** [comment]
The blog has been updated as per the suggestions.

**Comment by CreeyaSean** [comment]
Hi Kiril,
I have added more content and also got it reviewed by plagiarism. New file
has been uploaded.

Thank you.

**Comment by kkartunov** [comment]
@CreeyaSean I get "Plagiarism was detected" checking. Please, make sure it passes https://www.grammarly.com/plagiarism-checker

**Comment by CreeyaSean** [comment]
![image](https://user-images.githubusercontent.com/57211549/70770061-01c0cf80-1d94-11ea-8708-73de5f09ae6d.png)

Hi, The document has been checked now. Please find the updated document below: 
[My Journey with TopCoder Community.docx](https://github.com/topcoder-platform/thrive-submit/files/3959058/My.Journey.with.TopCoder.Community.docx)

**Comment by kkartunov** [comment]
@CreeyaSean I still get failed Plagiarism Check

**Comment by CreeyaSean** [comment]
> @CreeyaSean I still get failed Plagiarism Check

Hi, Van you please share the screenshot where you got this message, as it looks fine in my end.

**Comment by kkartunov** [comment]
@CreeyaSean https://drive.google.com/file/d/1pyRBWl-WRvcUpCkuqqtOrb66AKXx1Eo-/view

**Comment by CreeyaSean** [comment]
Hi, I am done with the Plagiarism check now. It is no more detected. 
Please find the updated document here: 

[My Journey with Top COder Community.docx](https://github.com/topcoder-platform/thrive-submit/files/3969195/My.Journey.with.Top.COder.Community.docx)

**Comment by kkartunov** [comment]
passed checks

**Comment by kkartunov** [comment]
@CreeyaSean thank You for your submission! We are looking for educational articles as written in the challenge spec, therefore, we can't accept this one for Thrive.

We glad that you have a great time with Topcoder and its community and wish you many successful challenges.

**Comment by CreeyaSean** [comment]
HI Kiril,

Thank you for the feedback, can we not publish it somewhere in TC's article
pool or a blog or Newsletter, wherever.

Regards,
Creeya
