### ISSUE TITLE
When to prefer React Native over Native Mobile technologies?

### ISSUE THREAD

**Issue by ArulmozhiV** [topcoder-platform/thrive-submit#73]
Development
[Thrive_React_Native.zip](https://github.com/topcoder-platform/thrive-submit/files/3955289/Thrive_React_Native.zip)

**Comment by kkartunov** [comment]
Passed PCheck and min len check

**Comment by billsedison** [comment]
The article is a bit obsolete. Like Airbnb has dropped React Native.

And there are a lot of similar discussions on Medium.
- https://medium.com/rebeldot/react-native-or-native-development-ios-android-what-should-you-choose-for-your-next-mobile-app-17b32b88dec9
- https://medium.com/mop-developers/mobile-app-development-react-native-vs-native-ios-android-49c5c168045b

I don't think we need a similar discussion article on Thrive. Also, the format of your article is not goo.d
