### ISSUE TITLE
Incoming power of javascript: Can Javascript outdo python

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/thrive-submit#74]
Hello, Kindly check the document below.
[Thrive final.zip](https://github.com/topcoder-platform/thrive-submit/files/3956882/Thrive.final.zip)

**Comment by kkartunov** [comment]
@Rokit12 Significant plagiarism was detected

**Comment by Rokit12** [comment]
Let me fix please

**Comment by Rokit12** [comment]
[TITLE_ Incoming power of javascript_ Can Javascript outdo python (2).docx](https://github.com/topcoder-platform/thrive-submit/files/3957692/TITLE_.Incoming.power.of.javascript_.Can.Javascript.outdo.python.2.docx)
Check this one please

**Comment by kkartunov** [comment]
@Rokit12 I get "Significant plagiarism was detected"

**Comment by Rokit12** [comment]
okay i will rewrite from scratch
