### ISSUE TITLE
Difference between User Interface (UI) and User Experience (UX)

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#75]
This is my new article. Please check

[Difference between User Interface (UI) and User Experience (UX).docx](https://github.com/topcoder-platform/thrive-submit/files/3957450/Difference.between.User.Interface.UI.and.User.Experience.UX.docx)

**Comment by kkartunov** [comment]
@KakaIdan Plagiarism was detected

**Comment by KakaIdan** [comment]
This is my improved article. please check

[Difference between User Interface (UI) and User Experience (UX).docx](https://github.com/topcoder-platform/thrive-submit/files/3958828/Difference.between.User.Interface.UI.and.User.Experience.UX.docx)

**Comment by kkartunov** [comment]
@KakaIdan I still get "Plagiarism was detected"
Please make sure all your submissions pass the test https://www.grammarly.com/plagiarism-checker before you submit!

**Comment by KakaIdan** [comment]
check please
[Difference between User Interface (UI) and User Experience (UX).docx](https://github.com/topcoder-platform/thrive-submit/files/3973244/Difference.between.User.Interface.UI.and.User.Experience.UX.docx)

**Comment by kkartunov** [comment]
passes now

**Comment by Dara-K** [comment]
Sorry! We already have an article on this theme on THRIVE and Blog: https://www.topcoder.com/ux-vs-ui-in-mobile-app-development/
