### ISSUE TITLE
Various kinds of graphic media

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#76]
This is my new article. Please check

[Various kinds of graphic media.docx](https://github.com/topcoder-platform/thrive-submit/files/3957456/Various.kinds.of.graphic.media.docx)

**Comment by kkartunov** [comment]
@KakaIdan Plagiarism was detected

**Comment by KakaIdan** [comment]
This is my improved article. please check

[Various kinds of graphic media.docx](https://github.com/topcoder-platform/thrive-submit/files/3958876/Various.kinds.of.graphic.media.docx)

**Comment by kkartunov** [comment]
@KakaIdan I am still getting "Plagiarism was detected"

**Comment by KakaIdan** [comment]
Where is my mistake? on that website, I have passed the plagiarism selection
![image](https://user-images.githubusercontent.com/58554510/70934602-d8908f80-2070-11ea-9eb4-89786173d1e0.png)

**Comment by kkartunov** [comment]
@KakaIdan https://www.grammarly.com/plagiarism-checker
