### ISSUE TITLE
Photoshop functions and uses in graphic design

### ISSUE THREAD

**Issue by KakaIdan** [topcoder-platform/thrive-submit#77]
This is my latest article. please check and give me feedback

[Photoshop functions and uses in graphic design (Wildan Abdul Azis).docx](https://github.com/topcoder-platform/thrive-submit/files/3959542/Photoshop.functions.and.uses.in.graphic.design.Wildan.Abdul.Azis.docx)

**Comment by kkartunov** [comment]
@KakaIdan I get Plagiarism was detected

**Comment by KakaIdan** [comment]
This is the result of my revision. please check

[Photoshop functions and uses in graphic design.docx](https://github.com/topcoder-platform/thrive-submit/files/3963911/Photoshop.functions.and.uses.in.graphic.design.docx)

**Comment by kkartunov** [comment]
@KakaIdan I still get "Plagiarism was detected" on this submission.

**Comment by KakaIdan** [comment]
Where is my mistake? on that website, I have passed the plagiarism selection
![image](https://user-images.githubusercontent.com/58554510/70934787-489f1580-2071-11ea-9fd0-7ff4a3ef2cd9.png)

**Comment by kkartunov** [comment]
@KakaIdan it should pass the test here https://www.grammarly.com/plagiarism-checker
