### ISSUE TITLE
Data Science-Reinforcement Learning Algorithms

### ISSUE THREAD

**Issue by t0070926** [topcoder-platform/thrive-submit#82]
[Data Science-Reinforcement Learning Algorithms.docx](https://github.com/topcoder-platform/thrive-submit/files/3963947/Data.Science-Reinforcement.Learning.Algorithms.docx)

**Comment by kkartunov** [comment]
@t0070926 Significant plagiarism was detected

**Comment by t0070926** [comment]
[Data.Science-Reinforcement.Learning.Algorithms.docx](https://github.com/topcoder-platform/thrive-submit/files/3964357/Data.Science-Reinforcement.Learning.Algorithms.docx)

**Comment by t0070926** [comment]
Verified through plagiarism tool its fine now

**Comment by kkartunov** [comment]
@t0070926 please do verify all your submissions before submitting. Thanks

**Comment by harshitmehta123** [comment]
The whole article is copied and edited from here: http://www.aionlinecourse.com/tutorial/machine-learning/reinforcement-learning.
