### ISSUE TITLE
Getting started with Jupyter notebook

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/thrive-submit#86]
Category: Data Science

[getting_started_jupyter.md.zip](https://github.com/topcoder-platform/thrive-submit/files/3964661/getting_started_jupyter.md.zip)

**Comment by kkartunov** [comment]
passed PCheck and min length check.

**Comment by harshitmehta123** [comment]
Duplicate of #64 
@anu0012 to merge with #64
