### ISSUE TITLE
LET’S REGISTER FOR A CHALLENGE IN TOPCODER

### ISSUE THREAD

**Issue by manju055** [topcoder-platform/thrive-submit#9]
[TOPCODER - Help Articles.zip](https://github.com/topcoder-platform/thrive-submit/files/3921130/TOPCODER.-.Help.Articles.zip)

**Comment by manju055** [comment]
TRACK CATEGORY:  TOPCODER
SUBCATEGORY: Help Articles 
TAGS: How-To

**Comment by kkartunov** [comment]
Passed Plagiarism.

**Comment by kkartunov** [comment]
@manju055 thank you for this submission. Unfortunately, we do have a related article on the subject in the Help Center thus can't accept this one.

**Comment by manju055** [comment]
That's Okay. Thank you for reviewing my article.
