### ISSUE TITLE
List of The Best Wireframe Tools for UI/UX Designers in 2019

### ISSUE THREAD

**Issue by hasanozie** [topcoder-platform/thrive-submit#91]
Track Category: Design

[Hasanozie - List of The Best Wireframe Tools for UI UX Designers in 2019.docx](https://github.com/topcoder-platform/thrive-submit/files/3967359/Hasanozie.-.List.of.The.Best.Wireframe.Tools.for.UI.UX.Designers.in.2019.docx)

**Comment by kkartunov** [comment]
passed PCheck and min len check

**Comment by Dara-K** [comment]
This article has a good research done, but I don't it will be very helpful for our members for 3 reasons:
1. We are moving away from wireframe challenges (as you saw we have fewer these days)
2. The allowed tools in challenges: Axure, Sketch, XD are not mentioned. Sketch and XD are not truly for prototyping, but the ones listed in the articles are not allowed in competitions.
3. Most of the members do the sketches/ wireframes on paper.
Sorry!

**Comment by hasanozie** [comment]
Thank you for reviewing this article :)
